-- ============================================================
--  GamePrep — Question Seed Script v2
--  DB: gameprep_db   Table: questions
--  20 MCQ + 5 CODING per topic per difficulty
--  18 topics x 3 difficulties x 25 = 1350 questions
--  Coding languages: Java(OOP) | C++(DSA) | Bash(OS) | SQL(DBMS)
-- ============================================================

USE gameprep_db;
TRUNCATE TABLE questions;

INSERT INTO questions (title, description, type, difficulty, prep_field, topic, options_json, correct_answer) VALUES

-- ================================================================
--  OOP / CLASSES  —  EASY
-- ================================================================
('Class Blueprint','What is a class in Java?','MCQ','EASY','OOP','Classes','["A blueprint for creating objects","An instance of an object","A compiled binary file","A data type on the stack"]','A blueprint for creating objects'),
('new Keyword','Which keyword is used to create a new object in Java?','MCQ','EASY','OOP','Classes','["create","object","new","make"]','new'),
('Constructor Purpose','What is the primary purpose of a constructor?','MCQ','EASY','OOP','Classes','["To destroy an object","To initialize a newly created object","To declare class fields","To define class behavior only"]','To initialize a newly created object'),
('this Keyword','What does the ''this'' keyword refer to inside an instance method?','MCQ','EASY','OOP','Classes','["The parent class","The current object instance","The current method","The class definition"]','The current object instance'),
('Int Default Value','What is the default value of an uninitialized int instance field?','MCQ','EASY','OOP','Classes','["null","undefined","0","-1"]','0'),
('Private Modifier','Which access modifier restricts access to within the same class only?','MCQ','EASY','OOP','Classes','["public","protected","private","default"]','private'),
('Public Modifier','Which access modifier allows access from any other class?','MCQ','EASY','OOP','Classes','["private","protected","public","package"]','public'),
('Class Naming','What naming convention is used for Java class names?','MCQ','EASY','OOP','Classes','["camelCase","snake_case","PascalCase (UpperCamelCase)","ALL_CAPS"]','PascalCase (UpperCamelCase)'),
('Multiple Constructors','Can a single Java class have more than one constructor?','MCQ','EASY','OOP','Classes','["No","Yes, through constructor overloading","Yes, but only same parameters","No, constructors are inherited"]','Yes, through constructor overloading'),
('Object Storage','Objects created with ''new'' are stored in which memory area?','MCQ','EASY','OOP','Classes','["Stack","Code segment","Heap","CPU register"]','Heap'),
('Instance Variable','An instance variable is declared:','MCQ','EASY','OOP','Classes','["Inside a method","Inside a class but outside any method","With the static keyword","Globally outside any class"]','Inside a class but outside any method'),
('Default Constructor','If you define no constructor, Java provides:','MCQ','EASY','OOP','Classes','["Nothing","A no-argument default constructor","A constructor with all fields as parameters","A static factory method"]','A no-argument default constructor'),
('Constructor Return','What is the return type of a Java constructor?','MCQ','EASY','OOP','Classes','["void","int","The class type","Constructors have no return type"]','Constructors have no return type'),
('toString Default','Printing an object without overriding toString() shows:','MCQ','EASY','OOP','Classes','["null","Class name only","ClassName@HexHashCode","A compilation error"]','ClassName@HexHashCode'),
('Reference Type','In Dog d = new Dog(); what type is variable d?','MCQ','EASY','OOP','Classes','["int","void","Object","Dog"]','Dog'),
('Static Usage','Which members can be used without creating an object?','MCQ','EASY','OOP','Classes','["private members","instance members","static members","final members"]','static members'),
('Null Default','Default value of an object reference field (e.g. String) is:','MCQ','EASY','OOP','Classes','["empty string","0","undefined","null"]','null'),
('Valid Declaration','Which is a valid Java class declaration?','MCQ','EASY','OOP','Classes','["class = MyClass {}","public class MyClass {}","MyClass public class {}","define class MyClass"]','public class MyClass {}'),
('Field vs Local','Key difference between a field and a local variable:','MCQ','EASY','OOP','Classes','["Fields are faster","Fields belong to class/object; locals belong to a method","Locals are public by default","Fields cannot be initialized"]','Fields belong to class/object; locals belong to a method'),
('Object Count','Can multiple objects be created from one class?','MCQ','EASY','OOP','Classes','["No","Yes, unlimited","Yes, but max 10","Yes, but they share memory"]','Yes, unlimited'),
-- EASY CODING
('Declare a Class','Write the Java declaration for a public class named Animal (empty body).','CODING','EASY','OOP','Classes',NULL,'public class Animal {}'),
('Declare a Field','Declare a private integer field named age inside a Java class.','CODING','EASY','OOP','Classes',NULL,'private int age;'),
('No-Arg Constructor','Write a no-argument constructor for class Book (empty body).','CODING','EASY','OOP','Classes',NULL,'public Book() {}'),
('Create Object','Write the Java statement to create a Car object named myCar.','CODING','EASY','OOP','Classes',NULL,'Car myCar = new Car();'),
('Print Hello','Write the Java statement to print Hello to the console.','CODING','EASY','OOP','Classes',NULL,'System.out.println("Hello");'),

-- ================================================================
--  OOP / CLASSES  —  MEDIUM
-- ================================================================
('Static Belonging','A static member belongs to:','MCQ','MEDIUM','OOP','Classes','["Each individual object","The class itself, shared across all instances","Only the first object","The subclass only"]','The class itself, shared across all instances'),
('Constructor Overloading','Constructor overloading means:','MCQ','MEDIUM','OOP','Classes','["Inheriting constructors","Multiple constructors with different parameter lists","Calling another constructor","A constructor with no body"]','Multiple constructors with different parameter lists'),
('final Class','Declaring a class final prevents:','MCQ','MEDIUM','OOP','Classes','["Instantiation","Subclassing","Field modification","Method calling"]','Subclassing'),
('this() Call','this() inside a constructor calls:','MCQ','MEDIUM','OOP','Classes','["The parent constructor","Another constructor in the same class","The current object method","A static initializer"]','Another constructor in the same class'),
('equals vs ==','Difference between == and equals() in Java:','MCQ','MEDIUM','OOP','Classes','["They are identical","== compares references; equals() compares content (overridable)","equals() compares references; == compares content","== works only for primitives"]','== compares references; equals() compares content (overridable)'),
('hashCode Contract','If two objects are equals(), their hashCodes must be:','MCQ','MEDIUM','OOP','Classes','["Different","The same","Unrelated","Zero"]','The same'),
('Immutable Class','Which makes a class immutable in Java?','MCQ','MEDIUM','OOP','Classes','["public fields + no constructor","final class + final fields + no setters","abstract class + private fields","static class + synchronized methods"]','final class + final fields + no setters'),
('Static Block','A static initialization block executes:','MCQ','MEDIUM','OOP','Classes','["Every time an object is created","Once, when the class is first loaded","Only when called explicitly","When the program ends"]','Once, when the class is first loaded'),
('Wrapper Class','Wrapper class for primitive int is:','MCQ','MEDIUM','OOP','Classes','["IntClass","IntWrapper","Integer","Num"]','Integer'),
('Anonymous Object','An anonymous object is:','MCQ','MEDIUM','OOP','Classes','["An object of an anonymous class","An object created without assigning to a variable","An object with no fields","An object inside a method always"]','An object created without assigning to a variable'),
('Object Class','Every Java class implicitly extends:','MCQ','MEDIUM','OOP','Classes','["Class","Runnable","Serializable","Object"]','Object'),
('toString Best Practice','Best practice for overriding toString():','MCQ','MEDIUM','OOP','Classes','["Return null","Return class name","Return meaningful string of object state","Return hashCode"]','Return meaningful string of object state'),
('Static Method Access','A static method can directly access:','MCQ','MEDIUM','OOP','Classes','["All instance fields","Only static fields and methods","Only final fields","Only public instance methods"]','Only static fields and methods'),
('Inner Class Access','A non-static inner class has access to:','MCQ','MEDIUM','OOP','Classes','["Only static outer members","All members (including private) of the outer class","Only public outer members","Nothing from the outer class"]','All members (including private) of the outer class'),
('GC Eligibility','An object becomes eligible for GC when:','MCQ','MEDIUM','OOP','Classes','["delete() is called","No more reachable references point to it","Its constructor completes","It is moved to stack"]','No more reachable references point to it'),
('Method Chaining','Method chaining is achieved when methods return:','MCQ','MEDIUM','OOP','Classes','["void","null","this (the current object)","A new object always"]','this (the current object)'),
('Constructor Inherited','Are constructors inherited by subclasses?','MCQ','MEDIUM','OOP','Classes','["Yes, all","No, constructors are not inherited","Only default constructor","Only if public"]','No, constructors are not inherited'),
('final Field','A final instance field must be initialized:','MCQ','MEDIUM','OOP','Classes','["At declaration or in every constructor","Only at declaration","Only in a static block","Only via setter"]','At declaration or in every constructor'),
('Fluent Pattern','StringBuilder.append("a").append("b") uses which pattern?','MCQ','MEDIUM','OOP','Classes','["Factory","Singleton","Fluent/Method Chaining","Observer"]','Fluent/Method Chaining'),
('Static this Error','Which causes a compile error?','MCQ','MEDIUM','OOP','Classes','["int x=5; in a static method","static int y=10;","this.name in a static method","String s=\"hi\"; in a static method"]','this.name in a static method'),
-- MEDIUM CODING
('Parameterized Constructor','Write a constructor for class Person accepting String name and assigning to field name.','CODING','MEDIUM','OOP','Classes',NULL,'public Person(String name) { this.name = name; }'),
('Override toString','Override toString() to return the value of String field name.','CODING','MEDIUM','OOP','Classes',NULL,'@Override public String toString() { return name; }'),
('Getter Method','Write a public getter for private String field name.','CODING','MEDIUM','OOP','Classes',NULL,'public String getName() { return name; }'),
('Setter Method','Write a public setter for private String field name.','CODING','MEDIUM','OOP','Classes',NULL,'public void setName(String name) { this.name = name; }'),
('Static Counter','Declare a private static int field count initialized to 0.','CODING','MEDIUM','OOP','Classes',NULL,'private static int count = 0;'),

-- ================================================================
--  OOP / CLASSES  —  HARD
-- ================================================================
('Singleton volatile','Thread-safe Singleton via double-checked locking requires the instance field to be:','MCQ','HARD','OOP','Classes','["final","static","volatile","synchronized"]','volatile'),
('Covariant Return','Covariant return types allow an overriding method to return:','MCQ','HARD','OOP','Classes','["A supertype","A subtype of the parent return type","void","Any checked exception"]','A subtype of the parent return type'),
('Type Erasure','Java type erasure means:','MCQ','HARD','OOP','Classes','["Generic types are retained at runtime","Generic types are removed at compile time, replaced with Object or bounds","Generics cause extra class files","JVM enforces generics at runtime"]','Generic types are removed at compile time, replaced with Object or bounds'),
('Shallow Copy','A shallow copy of an object:','MCQ','HARD','OOP','Classes','["Copies all referenced objects recursively","Copies primitive fields; reference fields point to the same objects","Creates a fully independent object","Is always performed by clone()"]','Copies primitive fields; reference fields point to the same objects'),
('Reflection API','Java Reflection API allows:','MCQ','HARD','OOP','Classes','["Compile code at runtime","Inspect and modify classes, fields, and methods at runtime","Only read class metadata","Replace bytecode at load time"]','Inspect and modify classes, fields, and methods at runtime'),
('WeakReference GC','A WeakReference is eligible for GC:','MCQ','HARD','OOP','Classes','["Never","Only when JVM exits","When no strong references point to it","Only after finalize() is called"]','When no strong references point to it'),
('Sealed Class','Sealed classes (Java 17+) restrict:','MCQ','HARD','OOP','Classes','["Which classes can access members","Which classes can extend or implement it","How many instances can be created","How many methods it can have"]','Which classes can extend or implement it'),
('Record Type','A Java Record auto-generates:','MCQ','HARD','OOP','Classes','["Abstract methods","Default constructor only","Constructor, getters, equals, hashCode, and toString","Static factory methods"]','Constructor, getters, equals, hashCode, and toString'),
('Dynamic Proxy','Java dynamic proxies (java.lang.reflect.Proxy) can only proxy:','MCQ','HARD','OOP','Classes','["Abstract classes","Concrete classes","Interfaces","Final classes"]','Interfaces'),
('Marker Interface','A marker interface has:','MCQ','HARD','OOP','Classes','["Exactly one method","Only static methods","No methods — signals metadata to JVM or frameworks","Only default methods"]','No methods — signals metadata to JVM or frameworks'),
('ClassLoader Order','JVM ClassLoader delegation order is:','MCQ','HARD','OOP','Classes','["App→Extension→Bootstrap","Bootstrap→Extension→App","Extension→Bootstrap→App","App→Bootstrap→Extension"]','Bootstrap→Extension→App'),
('Object Pool','Object Pool pattern is used to:','MCQ','HARD','OOP','Classes','["Hide creation logic","Limit to one instance","Reuse expensive-to-create objects to reduce allocation overhead","Proxy method calls"]','Reuse expensive-to-create objects to reduce allocation overhead'),
('Flyweight','Flyweight pattern improves memory by:','MCQ','HARD','OOP','Classes','["Creating one instance per class","Sharing common intrinsic state among many fine-grained objects","Wrapping objects in a proxy","Delegating creation to a factory"]','Sharing common intrinsic state among many fine-grained objects'),
('Transient Keyword','The transient keyword marks a field to:','MCQ','HARD','OOP','Classes','["Never be GC-collected","Be excluded from serialization","Be visible across threads","Be constant"]','Be excluded from serialization'),
('String Pool','String literals in Java are automatically:','MCQ','HARD','OOP','Classes','["Stored on the stack","Interned in the String Pool on the heap","Garbage collected immediately","Encrypted"]','Interned in the String Pool on the heap'),
('Prototype Pattern','The Prototype pattern creates objects by:','MCQ','HARD','OOP','Classes','["Calling a constructor","Copying (cloning) an existing object","Using a factory class","Using DI"]','Copying (cloning) an existing object'),
('Lazy Init','Lazy initialization means:','MCQ','HARD','OOP','Classes','["Init in static block","Init in constructor always","Defer init until first access","Init with a default value"]','Defer init until first access'),
('Decorator Pattern','The Decorator pattern adds behavior by:','MCQ','HARD','OOP','Classes','["Subclassing","Wrapping the object in another implementing the same interface","Using reflection","Modifying the original class"]','Wrapping the object in another implementing the same interface'),
('Method Handle','MethodHandle (java.lang.invoke) provides:','MCQ','HARD','OOP','Classes','["Runtime code generation","A typed executable reference to a method, constructor, or field","DB connection pooling","Byte-level memory access"]','A typed executable reference to a method, constructor, or field'),
('Externalizable','Externalizable vs Serializable: Externalizable gives:','MCQ','HARD','OOP','Classes','["Default serialization","Full control via readExternal and writeExternal","Faster default performance","No need for serialVersionUID"]','Full control via readExternal and writeExternal'),
-- HARD CODING
('Singleton Pattern','Implement a basic non-thread-safe Singleton for class Config: write the private static instance field + getInstance() method (not the class wrapper).','CODING','HARD','OOP','Classes',NULL,'private static Config instance; public static Config getInstance() { if(instance==null) instance=new Config(); return instance; }'),
('Static Factory','Write a static factory method named of in class Person accepting String name returning a new Person.','CODING','HARD','OOP','Classes',NULL,'public static Person of(String name) { return new Person(name); }'),
('Copy Constructor','Write a copy constructor for class Person that copies the String field name from another Person.','CODING','HARD','OOP','Classes',NULL,'public Person(Person other) { this.name = other.name; }'),
('Immutable Field','Declare a private immutable (final) String field named id.','CODING','HARD','OOP','Classes',NULL,'private final String id;'),
('Override equals','Override equals() in Person to compare by int field id. Write the complete method.','CODING','HARD','OOP','Classes',NULL,'@Override public boolean equals(Object o) { if(this==o) return true; if(!(o instanceof Person)) return false; return this.id==((Person)o).id; }'),

-- ================================================================
--  OOP / INHERITANCE  —  EASY
-- ================================================================
('Extends Keyword','Java inheritance is declared using which keyword?','MCQ','EASY','OOP','Inheritance','["implements","inherits","extends","uses"]','extends'),
('Superclass','A class that is inherited from is called a:','MCQ','EASY','OOP','Inheritance','["Child","Subclass","Superclass","Interface"]','Superclass'),
('Subclass','The class that inherits from another is called a:','MCQ','EASY','OOP','Inheritance','["Superclass","Parent class","Abstract class","Subclass"]','Subclass'),
('super Keyword','The super keyword is used to:','MCQ','EASY','OOP','Inheritance','["Create a superclass object","Access parent class members and constructor","Delete child object","Call static methods"]','Access parent class members and constructor'),
('Single Inheritance','Java classes support:','MCQ','EASY','OOP','Inheritance','["Multiple inheritance via classes","Single inheritance via classes","No inheritance","Only interface inheritance"]','Single inheritance via classes'),
('Method Override','When a subclass provides its own version of a parent method, it is called:','MCQ','EASY','OOP','Inheritance','["Method overloading","Method hiding","Method overriding","Method shadowing"]','Method overriding'),
('Override Annotation','The @Override annotation:','MCQ','EASY','OOP','Inheritance','["Is mandatory for overriding","Tells the compiler this is an intentional override and catches mistakes","Prevents further overriding","Makes the method static"]','Tells the compiler this is an intentional override and catches mistakes'),
('super() Call','super() inside a constructor must be:','MCQ','EASY','OOP','Inheritance','["The last statement","The first statement","Anywhere in the constructor","In a static block"]','The first statement'),
('Inherited Members','A subclass inherits which members from the superclass?','MCQ','EASY','OOP','Inheritance','["Only public methods","Only private fields","All non-private members (public, protected, package-private)","All members including private"]','All non-private members (public, protected, package-private)'),
('final Class Inherit','A class declared final:','MCQ','EASY','OOP','Inheritance','["Cannot be instantiated","Cannot be inherited/subclassed","Cannot have methods","Cannot have fields"]','Cannot be inherited/subclassed'),
('IS-A Relationship','Inheritance models which relationship?','MCQ','EASY','OOP','Inheritance','["HAS-A","USES-A","IS-A","KNOWS-A"]','IS-A'),
('Diamond Problem','Java avoids the diamond problem for classes by:','MCQ','EASY','OOP','Inheritance','["Using virtual methods","Allowing multiple inheritance","Restricting classes to single inheritance","Using final classes only"]','Restricting classes to single inheritance'),
('Object Parent','Every Java class ultimately inherits from:','MCQ','EASY','OOP','Inheritance','["Runnable","Cloneable","Object","Base"]','Object'),
('Overriding Return Type','An overriding method''s return type must be:','MCQ','EASY','OOP','Inheritance','["Exactly the same or a subtype (covariant)","Exactly the same","Any type","void always"]','Exactly the same or a subtype (covariant)'),
('private Inherited','Private members of a superclass:','MCQ','EASY','OOP','Inheritance','["Are inherited and accessible directly","Are inherited but not directly accessible in the subclass","Are not inherited at all","Are made protected in subclass"]','Are inherited but not directly accessible in the subclass'),
('Constructor Inherit2','Constructors in Java:','MCQ','EASY','OOP','Inheritance','["Are inherited","Are not inherited","Are partially inherited","Are inherited only if public"]','Are not inherited'),
('Polymorphism Via','Runtime polymorphism in Java is achieved via:','MCQ','EASY','OOP','Inheritance','["Method overloading","Static binding","Method overriding and dynamic dispatch","Constructor chaining"]','Method overriding and dynamic dispatch'),
('Override Access','When overriding a method, the access modifier can be:','MCQ','EASY','OOP','Inheritance','["More restrictive","The same or less restrictive (broader)","Always public","Only the same"]','The same or less restrictive (broader)'),
('Abstract Must','An abstract method in a parent:','MCQ','EASY','OOP','Inheritance','["Must be called by the parent","Must be overridden by all concrete subclasses","Is optional to override","Cannot have parameters"]','Must be overridden by all concrete subclasses'),
('Multilevel Inherit','A → B → C where B extends A and C extends B is called:','MCQ','EASY','OOP','Inheritance','["Multiple inheritance","Hybrid inheritance","Multilevel inheritance","Hierarchical inheritance"]','Multilevel inheritance'),
-- EASY CODING
('Extend Class','Write a class Dog that extends Animal (empty body).','CODING','EASY','OOP','Inheritance',NULL,'public class Dog extends Animal {}'),
('Call super','Write the first statement of a Dog constructor that calls the Animal constructor with no args.','CODING','EASY','OOP','Inheritance',NULL,'super();'),
('Override Method','Write a bark() method in Dog overriding Animal''s bark() to print Woof!','CODING','EASY','OOP','Inheritance',NULL,'@Override public void bark() { System.out.println("Woof!"); }'),
('Superclass Ref','Write the Java statement to store a Dog object in an Animal reference variable named a.','CODING','EASY','OOP','Inheritance',NULL,'Animal a = new Dog();'),
('Call Parent Method','Inside Dog, write a call to the parent class''s eat() method.','CODING','EASY','OOP','Inheritance',NULL,'super.eat();'),

-- ================================================================
--  OOP / INHERITANCE  —  MEDIUM
-- ================================================================
('Method Hiding','When a subclass defines a static method with the same signature as a parent static method:','MCQ','MEDIUM','OOP','Inheritance','["It overrides the parent method","It is a compile error","The parent method is hidden, not overridden","Both methods coexist and both are called"]','The parent method is hidden, not overridden'),
('Abstract Class','An abstract class:','MCQ','MEDIUM','OOP','Inheritance','["Cannot have fields","Cannot be instantiated","Cannot have concrete methods","Must extend another abstract class"]','Cannot be instantiated'),
('Interface vs Abstract','An interface (pre-Java 8) differs from an abstract class in that:','MCQ','MEDIUM','OOP','Inheritance','["Interface can have constructors","Interface can only have abstract methods and constants","Interface can have private fields","Interface must be final"]','Interface can only have abstract methods and constants'),
('Default Interface Method','Java 8 default methods in interfaces allow:','MCQ','MEDIUM','OOP','Inheritance','["Fields in interfaces","Concrete method implementations in interfaces","Multiple constructors","Static fields in interfaces"]','Concrete method implementations in interfaces'),
('Upcasting Safe','Upcasting (child → parent reference) is:','MCQ','MEDIUM','OOP','Inheritance','["Always unsafe and needs cast","Always safe and implicit","Requires instanceof check","Possible only for abstract classes"]','Always safe and implicit'),
('Downcasting Risk','Downcasting (parent ref → child) may throw:','MCQ','MEDIUM','OOP','Inheritance','["NullPointerException","ClassCastException","ArithmeticException","StackOverflowError"]','ClassCastException'),
('instanceof Check','What does the instanceof operator check?','MCQ','MEDIUM','OOP','Inheritance','["Reference equality","If an object is an instance of a given class or interface","Field existence","Method existence"]','If an object is an instance of a given class or interface'),
('LSP','The Liskov Substitution Principle states:','MCQ','MEDIUM','OOP','Inheritance','["Subclasses must override all methods","Objects of a supertype should be replaceable with subtypes without breaking correctness","Interfaces must be small","Classes should not inherit"]','Objects of a supertype should be replaceable with subtypes without breaking correctness'),
('final Method','A final method in a parent class:','MCQ','MEDIUM','OOP','Inheritance','["Cannot be called","Cannot be overridden by subclasses","Cannot have parameters","Is always static"]','Cannot be overridden by subclasses'),
('Abstract No Body','An abstract method:','MCQ','MEDIUM','OOP','Inheritance','["Has a body","Has no body — just signature","Must be static","Must return void"]','Has no body — just signature'),
('Interface Multiple','A Java class can implement:','MCQ','MEDIUM','OOP','Inheritance','["Only one interface","Multiple interfaces","No interfaces if it extends a class","Only interfaces from the same package"]','Multiple interfaces'),
('Concrete Subclass','A concrete subclass must:','MCQ','MEDIUM','OOP','Inheritance','["Override all methods","Override all abstract methods from its abstract parent","Override only public methods","Have a no-arg constructor"]','Override all abstract methods from its abstract parent'),
('Super Field Access','To access a parent class field hidden by a subclass field with the same name:','MCQ','MEDIUM','OOP','Inheritance','["Use this.field","Use field directly","Use super.field","Field hiding is a compile error"]','Use super.field'),
('Constructor Chain','In a 3-level hierarchy (A→B→C), creating new C() calls constructors in order:','MCQ','MEDIUM','OOP','Inheritance','["C, B, A","A, B, C","B, C only","Only C"]','A, B, C'),
('Override Throws','An overriding method can:','MCQ','MEDIUM','OOP','Inheritance','["Throw broader checked exceptions","Throw the same or narrower checked exceptions","Throw any runtime exception only","Not throw any exception"]','Throw the same or narrower checked exceptions'),
('HAS-A vs IS-A','Composition (HAS-A) is preferred over inheritance (IS-A) when:','MCQ','MEDIUM','OOP','Inheritance','["The relationship is truly IS-A","Behavior varies independently at runtime","You need polymorphism","The subclass is in the same package"]','Behavior varies independently at runtime'),
('Interface Constants','Fields declared in an interface are implicitly:','MCQ','MEDIUM','OOP','Inheritance','["private and mutable","protected and final","public static final","private static final"]','public static final'),
('Marker Interface2','Which is an example of a marker interface in Java?','MCQ','MEDIUM','OOP','Inheritance','["Runnable","Comparable","Serializable","Iterable"]','Serializable'),
('Inherit Static','Static methods are NOT polymorphic because:','MCQ','MEDIUM','OOP','Inheritance','["They have no access to this","They are resolved at compile time, not runtime","They cannot be overridden at all","They are always final"]','They are resolved at compile time, not runtime'),
('Template Method','The Template Method design pattern uses:','MCQ','MEDIUM','OOP','Inheritance','["Composition exclusively","Abstract class defining algorithm skeleton; subclasses fill in steps","Interface with all methods","Static factory methods"]','Abstract class defining algorithm skeleton; subclasses fill in steps'),
-- MEDIUM CODING
('Abstract Method','Write an abstract method fly() with no body in abstract class Bird.','CODING','MEDIUM','OOP','Inheritance',NULL,'abstract void fly();'),
('Implement Interface','Write class Eagle implementing Flyable with a fly() method that prints Flying!','CODING','MEDIUM','OOP','Inheritance',NULL,'public class Eagle implements Flyable { public void fly() { System.out.println("Flying!"); } }'),
('Downcast Check','Write Java code to safely downcast Animal a to Dog d using instanceof.','CODING','MEDIUM','OOP','Inheritance',NULL,'if(a instanceof Dog) { Dog d = (Dog) a; }'),
('Override with super','Write speak() in Dog that calls super.speak() then prints Bark!','CODING','MEDIUM','OOP','Inheritance',NULL,'@Override public void speak() { super.speak(); System.out.println("Bark!"); }'),
('final Method2','Declare a final method named getId() returning int 1 in class Entity.','CODING','MEDIUM','OOP','Inheritance',NULL,'public final int getId() { return 1; }'),

-- ================================================================
--  OOP / INHERITANCE  —  HARD
-- ================================================================
('Diamond Default','Two interfaces A and B both provide default greet(). Class C implements both. C must:','MCQ','HARD','OOP','Inheritance','["Fails to compile unless C overrides greet()","Automatically picks interface A","Automatically picks interface B","Uses Object.greet()"]','Fails to compile unless C overrides greet()'),
('Bridge Pattern','The Bridge design pattern separates:','MCQ','HARD','OOP','Inheritance','["Creation from usage","Abstraction from implementation so they can vary independently","Behavior from state","Algorithm from data structure"]','Abstraction from implementation so they can vary independently'),
('Covariant Return2','A covariant return type means the overriding method returns a _____ of the parent return type.','MCQ','HARD','OOP','Inheritance','["supertype","narrower subtype","wider supertype","unrelated type"]','narrower subtype'),
('Sealed Permits','In a sealed class hierarchy, every direct subclass must be:','MCQ','HARD','OOP','Inheritance','["abstract","final, sealed, or non-sealed","public","in the same file"]','final, sealed, or non-sealed'),
('Strategy vs Template','Strategy uses ___ ; Template Method uses ___.','MCQ','HARD','OOP','Inheritance','["Composition; Inheritance","Inheritance; Composition","Both composition","Both inheritance"]','Composition; Inheritance'),
('Effective Java Item 18','Effective Java recommends favouring composition over inheritance because:','MCQ','HARD','OOP','Inheritance','["Inheritance is slow","Inheritance breaks encapsulation; subclass depends on parent internals","Composition is faster","Inheritance prevents polymorphism"]','Inheritance breaks encapsulation; subclass depends on parent internals'),
('Override vs Overload','Which statement about overriding vs overloading is TRUE?','MCQ','HARD','OOP','Inheritance','["Both are resolved at runtime","Overloading is resolved at compile time; overriding at runtime","Both are resolved at compile time","Overriding is resolved at compile time; overloading at runtime"]','Overloading is resolved at compile time; overriding at runtime'),
('Mixin via Interface','Java simulates mixins using:','MCQ','HARD','OOP','Inheritance','["Multiple class inheritance","Default methods in interfaces","Abstract classes","Generics"]','Default methods in interfaces'),
('Var Shadowing','When a subclass field shadows a parent field, the correct field is resolved by:','MCQ','HARD','OOP','Inheritance','["Runtime type of the object","Compile-time type of the reference variable","The most recent declaration","Random resolution"]','Compile-time type of the reference variable'),
('Polymorphic Field','Given Animal a = new Dog();, a.name accesses:','MCQ','HARD','OOP','Inheritance','["Dog.name always","Animal.name (field access is NOT polymorphic)","Causes ClassCastException","Causes NullPointerException"]','Animal.name (field access is NOT polymorphic)'),
('Constructor Visibility','A constructor can be package-private (no modifier). What does this mean?','MCQ','HARD','OOP','Inheritance','["No subclass can instantiate the class","Only classes in the same package can instantiate it","The class is effectively final","The class has no constructor"]','Only classes in the same package can instantiate it'),
('Enrich Default','When interface I has a default method foo(), and class A implements I and overrides foo(), class B extends A. B.foo() calls:','MCQ','HARD','OOP','Inheritance','["I''s default","A''s override","B''s own version if B overrides it; otherwise A''s","Causes compile error"]','B''s own version if B overrides it; otherwise A''s'),
('Proxy vs Decorator','Dynamic Proxy differs from Decorator in that:','MCQ','HARD','OOP','Inheritance','["Decorator only works on interfaces","Dynamic Proxy is created at runtime via reflection; Decorator is a compile-time wrapper","They are identical","Decorator requires inheritance"]','Dynamic Proxy is created at runtime via reflection; Decorator is a compile-time wrapper'),
('Open Closed','The Open/Closed Principle states:','MCQ','HARD','OOP','Inheritance','["Classes must be open for modification","Classes should be open for extension but closed for modification","Interfaces should be closed","Methods must be final"]','Classes should be open for extension but closed for modification'),
('Functional Interface','A functional interface has exactly:','MCQ','HARD','OOP','Inheritance','["No methods","One abstract method","Two methods","Only default methods"]','One abstract method'),
('Interface Segregation','The Interface Segregation Principle states:','MCQ','HARD','OOP','Inheritance','["One interface per project","Clients should not be forced to depend on methods they do not use","Interfaces should be large","Only abstract classes, no interfaces"]','Clients should not be forced to depend on methods they do not use'),
('Widening Narrowing','Widening reference conversion is:','MCQ','HARD','OOP','Inheritance','["Downcasting","Upcasting (subtype to supertype) — always implicit and safe","Casting primitive to object","Always requires explicit cast"]','Upcasting (subtype to supertype) — always implicit and safe'),
('Abstract Constructor','Abstract classes:','MCQ','HARD','OOP','Inheritance','["Cannot have constructors","Can have constructors (called via super() in subclass)","Must have only abstract constructors","Have default constructors only"]','Can have constructors (called via super() in subclass)'),
('Inherit Private Via','A subclass can access a parent''s private field:','MCQ','HARD','OOP','Inheritance','["Directly","Via public/protected getter methods in the parent","Using reflection only at runtime","Via super keyword"]','Via public/protected getter methods in the parent'),
('Interface Default Conflict','Class C extends A and implements I. Both A and I have foo(). Which wins?','MCQ','HARD','OOP','Inheritance','["I''s default always","A''s concrete method wins (class beats interface default)","Compile error always","Random"]','A''s concrete method wins (class beats interface default)'),
-- HARD CODING
('Resolve Diamond','Write how class C resolves the diamond conflict for greet(), calling interface A''s version.','CODING','HARD','OOP','Inheritance',NULL,'@Override public void greet() { A.super.greet(); }'),
('Sealed Class Declare','Declare a sealed class Shape that permits Circle and Rectangle.','CODING','HARD','OOP','Inheritance',NULL,'public sealed class Shape permits Circle, Rectangle {}'),
('Functional Interface2','Declare a functional interface Transformer with a single method int transform(int x).','CODING','HARD','OOP','Inheritance',NULL,'@FunctionalInterface public interface Transformer { int transform(int x); }'),
('Abstract Class2','Write an abstract class Vehicle with an abstract method start() and a concrete method stop() printing Stopped.','CODING','HARD','OOP','Inheritance',NULL,'public abstract class Vehicle { public abstract void start(); public void stop() { System.out.println("Stopped"); } }'),
('Final Override Prevent','Write a final method in class Base named compute() returning int 42 to prevent overriding.','CODING','HARD','OOP','Inheritance',NULL,'public final int compute() { return 42; }'),

-- ================================================================
--  OOP / POLYMORPHISM  —  EASY
-- ================================================================
('Poly Meaning','Polymorphism means:','MCQ','EASY','OOP','Polymorphism','["One form","Many classes","Many forms","Compile-time resolution only"]','Many forms'),
('Compile Time Poly','Method overloading is an example of:','MCQ','EASY','OOP','Polymorphism','["Runtime polymorphism","Compile-time polymorphism","Dynamic dispatch","Interface polymorphism"]','Compile-time polymorphism'),
('Runtime Poly','Method overriding is an example of:','MCQ','EASY','OOP','Polymorphism','["Compile-time polymorphism","Static polymorphism","Runtime polymorphism","No polymorphism"]','Runtime polymorphism'),
('Overloading Difference','Method overloading requires methods to have:','MCQ','EASY','OOP','Polymorphism','["Same name and same parameters","Same name but different parameters","Different names and same return type","Same name and same return type"]','Same name but different parameters'),
('Upcasting2','Storing a child object in a parent reference is called:','MCQ','EASY','OOP','Polymorphism','["Downcasting","Boxing","Upcasting","Coercion"]','Upcasting'),
('Dynamic Dispatch','JVM decides which overridden method to call at runtime — this is called:','MCQ','EASY','OOP','Polymorphism','["Static dispatch","Compile-time resolution","Dynamic method dispatch","Method hiding"]','Dynamic method dispatch'),
('Overload Return','Can two methods differ only in return type to be overloaded?','MCQ','EASY','OOP','Polymorphism','["Yes","No — compiler cannot distinguish by return type","Only if one is void","Only for static methods"]','No — compiler cannot distinguish by return type'),
('Interface Poly','Using an interface reference variable to call different implementations is an example of:','MCQ','EASY','OOP','Polymorphism','["Compile-time polymorphism","Runtime polymorphism","Static binding","Method hiding"]','Runtime polymorphism'),
('Overload Params','Which of these IS a valid overload of int add(int a, int b)?','MCQ','EASY','OOP','Polymorphism','["int add(int a, int b)","double add(double a, double b)","void add(int a, int b)","int add(int x, int y)"]','double add(double a, double b)'),
('Upcast Implicit','Upcasting in Java requires:','MCQ','EASY','OOP','Polymorphism','["Explicit cast","No cast — it is implicit","instanceof check","A try-catch block"]','No cast — it is implicit'),
('Array Poly','Animal[] zoo = {new Dog(), new Cat()}; zoo[0].sound() calls:','MCQ','EASY','OOP','Polymorphism','["Animal.sound()","Dog.sound() — resolved at runtime","Cat.sound()","Compile error"]','Dog.sound() — resolved at runtime'),
('Overload Auto','Auto-widening in overloaded method resolution means Java:','MCQ','EASY','OOP','Polymorphism','["Throws an error","Automatically widens primitive arguments to find the best match","Requires explicit cast","Picks a random method"]','Automatically widens primitive arguments to find the best match'),
('Static vs Dynamic','Static binding is used for:','MCQ','EASY','OOP','Polymorphism','["Overriding","Overloading and static/final/private methods","All methods","Interface methods"]','Overloading and static/final/private methods'),
('Poly Benefits','The main benefit of polymorphism is:','MCQ','EASY','OOP','Polymorphism','["Faster code execution","Write code that works with objects of different types via a common interface","Reduce number of classes","Avoid inheritance"]','Write code that works with objects of different types via a common interface'),
('Cannot Override','Which methods CANNOT be overridden?','MCQ','EASY','OOP','Polymorphism','["public methods","protected methods","private, static, and final methods","abstract methods"]','private, static, and final methods'),
('VTable','The JVM uses a virtual method table (vtable) to support:','MCQ','EASY','OOP','Polymorphism','["Static binding","Dynamic dispatch at runtime","Compile-time overloading","Constructor chaining"]','Dynamic dispatch at runtime'),
('Overload Ambiguity','int f(int a, double b) and int f(double a, int b) called with f(1,1) causes:','MCQ','EASY','OOP','Polymorphism','["Runtime exception","Calls the first method","Ambiguous method call compile error","Calls the second method"]','Ambiguous method call compile error'),
('Subtype Replace','The ability to use a Dog anywhere an Animal is expected is:','MCQ','EASY','OOP','Polymorphism','["Encapsulation","Polymorphism / subtype substitution","Abstraction","Reflection"]','Polymorphism / subtype substitution'),
('Overload Type Promo','For overloaded methods, Java promotes byte → short → int → long →:','MCQ','EASY','OOP','Polymorphism','["char","float → double","String","Object"]','float → double'),
('Poly OOP Pillar','Polymorphism is considered one of the four pillars of OOP. The others are:','MCQ','EASY','OOP','Polymorphism','["Encapsulation, Abstraction, Compilation","Encapsulation, Inheritance, Abstraction","Inheritance, Reflection, Generics","Abstraction, Serialization, Generics"]','Encapsulation, Inheritance, Abstraction'),
-- EASY CODING
('Overloaded Add','Write two overloaded methods named add: one takes two ints returning int sum, one takes two doubles returning double sum.','CODING','EASY','OOP','Polymorphism',NULL,'public int add(int a,int b){return a+b;} public double add(double a,double b){return a+b;}'),
('Upcast Statement','Write the statement to store a new Dog() in an Animal variable named a.','CODING','EASY','OOP','Polymorphism',NULL,'Animal a = new Dog();'),
('Override sound','Override method sound() in class Cat to print Meow!','CODING','EASY','OOP','Polymorphism',NULL,'@Override public void sound() { System.out.println("Meow!"); }'),
('Interface Ref','Write the statement to store a new Circle() (implementing Shape) in a Shape reference named s.','CODING','EASY','OOP','Polymorphism',NULL,'Shape s = new Circle();'),
('Call Overridden','Given Animal a = new Dog(); write the statement to call a.speak().','CODING','EASY','OOP','Polymorphism',NULL,'a.speak();'),

-- ================================================================
--  OOP / POLYMORPHISM  —  MEDIUM
-- ================================================================
('PECS','PECS stands for: Producer Extends Consumer ___','MCQ','MEDIUM','OOP','Polymorphism','["Extends","Super","Subtype","Covariant"]','Super'),
('Bounded Wildcard Extends','List<? extends Animal> allows:','MCQ','MEDIUM','OOP','Polymorphism','["Adding any Animal","Adding null and reading as Animal","Adding Dog or Cat","Modifying any element"]','Adding null and reading as Animal'),
('Wildcard Super','List<? super Dog> allows:','MCQ','MEDIUM','OOP','Polymorphism','["Reading as Dog","Adding Dog or its subtypes","Adding any Object","Reading as Object (only safe read type)"]','Adding Dog or its subtypes'),
('Pattern Matching instanceof','Java 16+ pattern matching instanceof Dog d means:','MCQ','MEDIUM','OOP','Polymorphism','["Always true","Tests type AND binds a variable d of type Dog in the true branch","Only tests type","Requires explicit cast after"]','Tests type AND binds a variable d of type Dog in the true branch'),
('Visitor Double Dispatch','The Visitor pattern achieves double dispatch by:','MCQ','MEDIUM','OOP','Polymorphism','["Using two for-loops","Calling accept(visitor) on element then visitor.visit(this) inside accept","Using two vtables","Using generics"]','Calling accept(visitor) on element then visitor.visit(this) inside accept'),
('Generic Method','A generic method <T> T identity(T t) returns:','MCQ','MEDIUM','OOP','Polymorphism','["An Object","A String always","The exact type T passed — works for any T","Only for primitives"]','The exact type T passed — works for any T'),
('Overriding with Generics','Overriding a generic method requires:','MCQ','MEDIUM','OOP','Polymorphism','["Same raw type only","The exact same type parameter signature","A wider type","Removing generics"]','The exact same type parameter signature'),
('Covariance Array','Java arrays are covariant, meaning Dog[] is a subtype of Animal[]. The risk is:','MCQ','MEDIUM','OOP','Polymorphism','["Compile-time error","ArrayStoreException at runtime if incompatible type stored","NullPointerException","No risk"]','ArrayStoreException at runtime if incompatible type stored'),
('Generic vs Raw','Using a raw type (e.g. List instead of List<String>):','MCQ','MEDIUM','OOP','Polymorphism','["Is identical to using List<Object>","Loses compile-time type safety","Improves performance","Is not allowed in Java"]','Loses compile-time type safety'),
('Enum Poly','Java enums can implement interfaces. This allows:','MCQ','MEDIUM','OOP','Polymorphism','["Multiple inheritance","Polymorphic behavior per enum constant","Static polymorphism only","No polymorphism"]','Polymorphic behavior per enum constant'),
('Lambda Poly','A lambda expression is an instance of a:','MCQ','MEDIUM','OOP','Polymorphism','["Class","Functional interface","Thread","Anonymous class only"]','Functional interface'),
('Method Ref','A method reference like String::length is equivalent to:','MCQ','MEDIUM','OOP','Polymorphism','["s -> s","s -> s.length()","s -> length(s)","() -> s.length()"]','s -> s.length()'),
('Wildcard Unbounded','List<?> means:','MCQ','MEDIUM','OOP','Polymorphism','["List of Object","List of any type — read-only; can add null","List of unknown size","List of primitives only"]','List of any type — read-only; can add null'),
('Generic Bound','<T extends Comparable<T>> means T must:','MCQ','MEDIUM','OOP','Polymorphism','["Extend a class Comparable","Implement the Comparable interface","Be a Number subtype","Be a primitive"]','Implement the Comparable interface'),
('Ad-hoc Poly','Overloading is called ad-hoc polymorphism because:','MCQ','MEDIUM','OOP','Polymorphism','["It is resolved randomly","Different behavior for different argument types — not a universal algorithm","It adapts at runtime","It uses vtable lookup"]','Different behavior for different argument types — not a universal algorithm'),
('Type Token','A Class<T> parameter is called a type token and is used to:','MCQ','MEDIUM','OOP','Polymorphism','["Create generics at runtime","Work around type erasure by passing Class objects explicitly","Avoid instanceof","Do upcasting"]','Work around type erasure by passing Class objects explicitly'),
('Functional Poly','Using different lambda implementations of the same functional interface is:','MCQ','MEDIUM','OOP','Polymorphism','["Method overloading","Parametric polymorphism","Ad-hoc polymorphism via lambdas","Not polymorphism"]','Ad-hoc polymorphism via lambdas'),
('Wildcard Capture','Wildcard capture error occurs when:','MCQ','MEDIUM','OOP','Polymorphism','["You try to add to List<?>","You read from List<?>","You pass List<?> to a method","You create a List<?>"]','You try to add to List<?>'),
('Erased Type','After type erasure, List<String> becomes:','MCQ','MEDIUM','OOP','Polymorphism','["List<Object>","List<String>","List (raw type)","String[]"]','List (raw type)'),
('Bridge Method','Java compiler generates bridge methods to support:','MCQ','MEDIUM','OOP','Polymorphism','["Default interface methods","Overriding with covariant return types and generics after erasure","Static methods","Constructor chaining"]','Overriding with covariant return types and generics after erasure'),
-- MEDIUM CODING
('Generic Method2','Write a generic static method named first that takes a List<T> and returns its first element.','CODING','MEDIUM','OOP','Polymorphism',NULL,'public static <T> T first(List<T> list) { return list.get(0); }'),
('Comparable Override','Write compareTo() in class Student (implementing Comparable<Student>) that compares by int field gpa, returning Integer.compare(this.gpa, other.gpa).','CODING','MEDIUM','OOP','Polymorphism',NULL,'@Override public int compareTo(Student other) { return Integer.compare(this.gpa, other.gpa); }'),
('Lambda Assign','Write a lambda for Runnable r that prints Running! when run.','CODING','MEDIUM','OOP','Polymorphism',NULL,'Runnable r = () -> System.out.println("Running!");'),
('Bounded Generic','Write a method max that takes two T extends Comparable<T> args and returns the greater one.','CODING','MEDIUM','OOP','Polymorphism',NULL,'public static <T extends Comparable<T>> T max(T a, T b) { return a.compareTo(b) >= 0 ? a : b; }'),
('Method Reference2','Write a Comparator<String> using method reference that compares by natural order (String::compareTo).','CODING','MEDIUM','OOP','Polymorphism',NULL,'Comparator<String> cmp = String::compareTo;'),

-- ================================================================
--  OOP / POLYMORPHISM  —  HARD
-- ================================================================
('HKT Java','Higher-kinded types (e.g. Functor<F<A>>) are NOT directly supported in Java because:','MCQ','HARD','OOP','Polymorphism','["Java has no generics","Java generics are not higher-kinded — F cannot be generic","Java is not functional","Java uses type erasure only"]','Java generics are not higher-kinded — F cannot be generic'),
('Phantom Type','Phantom types are type parameters that:','MCQ','HARD','OOP','Polymorphism','["Are erased and never used at runtime — purely compile-time markers","Are always int","Replace generics","Require Reflection"]','Are erased and never used at runtime — purely compile-time markers'),
('Contravariance Consumer','If you need to write (add) Dogs to a list, the parameter should be:','MCQ','HARD','OOP','Polymorphism','["List<Dog>","List<? extends Dog>","List<? super Dog>","List<Animal>"]','List<? super Dog>'),
('Recursive Generic','The pattern class Node<T extends Comparable<T>> uses:','MCQ','HARD','OOP','Polymorphism','["Type erasure only","Recursive generics / F-bounded quantification","Raw types","Unchecked cast"]','Recursive generics / F-bounded quantification'),
('Wild Inference','Given void copy(List<? extends T> src, List<? super T> dst), calling copy requires T to be:','MCQ','HARD','OOP','Polymorphism','["Explicitly specified always","Inferred by the compiler from context","Set to Object","Set to Comparable"]','Inferred by the compiler from context'),
('Structural Typing','Java uses nominal typing. A structural type system would allow:','MCQ','HARD','OOP','Polymorphism','["Only interface-based typing","Any object with matching method signatures to satisfy a type, regardless of declared type (like Go/TypeScript)","Generics only","Reflection-based typing"]','Any object with matching method signatures to satisfy a type, regardless of declared type (like Go/TypeScript)'),
('Intersection Type','In Java, <T extends Comparable<T> & Serializable> declares a type that:','MCQ','HARD','OOP','Polymorphism','["Is invalid","Must implement both Comparable and Serializable","Must be a class not an interface","Requires casting"]','Must implement both Comparable and Serializable'),
('Variance Liskov','Arrays covariance is considered a design flaw because it violates:','MCQ','HARD','OOP','Polymorphism','["Singleton principle","The principle that if S is a subtype of T, operations on T should be substitutable for S (leads to ArrayStoreException)","Encapsulation","Method hiding rules"]','The principle that if S is a subtype of T, operations on T should be substitutable for S (leads to ArrayStoreException)'),
('Self Type Java','Java does NOT have a native self type, but it is simulated using:','MCQ','HARD','OOP','Polymorphism','["this keyword","Recursive generic <T extends Builder<T>>","Abstract class","Override annotation"]','Recursive generic <T extends Builder<T>>'),
('Mixed Dispatch','Double dispatch in Java is typically implemented via:','MCQ','HARD','OOP','Polymorphism','["Two method calls","Visitor pattern: element.accept(visitor) then visitor.visit(concreteElement)","Reflection","Two instanceof checks"]','Visitor pattern: element.accept(visitor) then visitor.visit(concreteElement)'),
('Raw Type Heap Pollution','Using a raw type can cause:','MCQ','HARD','OOP','Polymorphism','["Compile error always","Heap pollution — a reference of parameterized type refers to a wrong type, causing ClassCastException at unexpected points","StackOverflow","NullPointer only"]','Heap pollution — a reference of parameterized type refers to a wrong type, causing ClassCastException at unexpected points'),
('Existential Type','List<?> is Java''s approximation of an existential type because:','MCQ','HARD','OOP','Polymorphism','["It has no elements","The actual type argument is hidden and unknown to the caller — it exists but is not named","It works like List<Object>","It prevents reading"]','The actual type argument is hidden and unknown to the caller — it exists but is not named'),
('Variance Summary','Java generics are invariant meaning:','MCQ','HARD','OOP','Polymorphism','["List<Dog> is a subtype of List<Animal>","List<Dog> is not a subtype of List<Animal> even though Dog extends Animal","List<Animal> is a subtype of List<Dog>","Generic types cannot be subtyped"]','List<Dog> is not a subtype of List<Animal> even though Dog extends Animal'),
('Safe Varargs','@SafeVarargs annotation suppresses:','MCQ','HARD','OOP','Polymorphism','["Null pointer warnings","Unchecked warnings for generic varargs that do not cause heap pollution","Override warnings","Deprecation warnings"]','Unchecked warnings for generic varargs that do not cause heap pollution'),
('Type Witness','In Java, a type witness like Collections.<String>emptyList() is used to:','MCQ','HARD','OOP','Polymorphism','["Cast the result","Explicitly provide a type argument when inference fails","Override a generic method","Use raw types"]','Explicitly provide a type argument when inference fails'),
('Reification','Unlike generics, arrays in Java are reified, meaning:','MCQ','HARD','OOP','Polymorphism','["Arrays use type erasure","Array type information is retained at runtime and checked on element store","Arrays are covariant at compile time only","Arrays cannot hold references"]','Array type information is retained at runtime and checked on element store'),
('Wildcard Guidelines','According to Effective Java, you should use wildcard types on:','MCQ','HARD','OOP','Polymorphism','["Field declarations","Method parameters (producer: ? extends, consumer: ? super), not return types","Return types always","Class declarations"]','Method parameters (producer: ? extends, consumer: ? super), not return types'),
('Enum Abstract','An enum with an abstract method is useful because:','MCQ','HARD','OOP','Polymorphism','["It creates an abstract enum class","Each constant provides its own implementation — per-constant polymorphic behavior","It allows inheritance","It makes enum non-final"]','Each constant provides its own implementation — per-constant polymorphic behavior'),
('Cast at Erasure','After type erasure, the compiler inserts:','MCQ','HARD','OOP','Polymorphism','["Runtime type checks everywhere","Checkcast bytecode instructions (casts) at usage points","New classes per type","Nothing"]','Checkcast bytecode instructions (casts) at usage points'),
('Generic Return Avoid','Effective Java recommends not using wildcard types in:','MCQ','HARD','OOP','Polymorphism','["Parameter positions","Return types — it forces users to deal with wildcards","Field positions","Local variables"]','Return types — it forces users to deal with wildcards'),
-- HARD CODING
('Variance Producer','Write a method printAll that takes List<? extends Animal> and prints each element.','CODING','HARD','OOP','Polymorphism',NULL,'public void printAll(List<? extends Animal> list) { for(Animal a : list) System.out.println(a); }'),
('Variance Consumer','Write a method addDog that takes List<? super Dog> and adds a new Dog to it.','CODING','HARD','OOP','Polymorphism',NULL,'public void addDog(List<? super Dog> list) { list.add(new Dog()); }'),
('Recursive Builder','Write the return type declaration of a Builder method setName so the builder supports fluent chaining with the recursive generic pattern <B extends Builder<B>>.','CODING','HARD','OOP','Polymorphism',NULL,'public B setName(String name) { this.name = name; return (B) this; }'),
('Intersection Bound','Write a generic method serialize that accepts T extends Comparable<T> & Serializable and returns a String of t.','CODING','HARD','OOP','Polymorphism',NULL,'public <T extends Comparable<T> & Serializable> String serialize(T t) { return t.toString(); }'),
('Visitor Accept','Write the accept method in a concrete class Circle implementing Element, calling visitor.visit(this).','CODING','HARD','OOP','Polymorphism',NULL,'@Override public void accept(Visitor visitor) { visitor.visit(this); }'),

-- ================================================================
--  OOP / ENCAPSULATION  —  EASY
-- ================================================================
('Encap Definition','Encapsulation in OOP means:','MCQ','EASY','OOP','Encapsulation','["Using many classes","Bundling data and methods together and restricting direct access to internals","Making all methods static","Hiding methods only"]','Bundling data and methods together and restricting direct access to internals'),
('Private Field','To encapsulate a class field, you should declare it:','MCQ','EASY','OOP','Encapsulation','["public","static","private","protected"]','private'),
('Getter Purpose','A getter method:','MCQ','EASY','OOP','Encapsulation','["Modifies the field value","Returns the value of a private field","Creates a new object","Deletes the field"]','Returns the value of a private field'),
('Setter Purpose','A setter method:','MCQ','EASY','OOP','Encapsulation','["Returns the field value","Allows controlled modification of a private field","Creates a new object","Is always optional"]','Allows controlled modification of a private field'),
('Encap Benefit','The main benefit of encapsulation is:','MCQ','EASY','OOP','Encapsulation','["Faster execution","You can change internal implementation without breaking callers","Allows multiple inheritance","Reduces memory usage"]','You can change internal implementation without breaking callers'),
('Accessor Naming','Getter for a boolean field active follows which naming convention?','MCQ','EASY','OOP','Encapsulation','["getActive()","active()","isActive()","fetchActive()"]','isActive()'),
('Encap Access','Which access modifier is most encapsulating?','MCQ','EASY','OOP','Encapsulation','["public","protected","default","private"]','private'),
('Setter Validation','A setter can include validation logic to:','MCQ','EASY','OOP','Encapsulation','["Speed up the program","Prevent invalid data from being set","Replace constructors","Auto-log changes"]','Prevent invalid data from being set'),
('Encap vs Abstract','Encapsulation hides ___ ; abstraction hides ___','MCQ','EASY','OOP','Encapsulation','["Implementation; implementation","Implementation details inside an object; implementation from the user","Data; methods","Methods; data"]','Implementation details inside an object; implementation from the user'),
('String Encap','String in Java is immutable. This is a form of:','MCQ','EASY','OOP','Encapsulation','["Polymorphism","Inheritance","Encapsulation (internal state cannot be changed after creation)","Abstraction"]','Encapsulation (internal state cannot be changed after creation)'),
('Default Access','Package-private (no modifier) access means:','MCQ','EASY','OOP','Encapsulation','["Accessible everywhere","Accessible only within the same class","Accessible within the same package","Accessible in subclasses only"]','Accessible within the same package'),
('Protected Access','Protected access means visible:','MCQ','EASY','OOP','Encapsulation','["Only same class","Same class and same package only","Same package and subclasses","Everywhere"]','Same package and subclasses'),
('Bean Convention','JavaBeans require fields to be:','MCQ','EASY','OOP','Encapsulation','["public","static","private with public getters and setters","final"]','private with public getters and setters'),
('Encap Break','Which of the following BREAKS encapsulation?','MCQ','EASY','OOP','Encapsulation','["Using private fields","Using getters","Returning a direct reference to a mutable internal field","Using setters"]','Returning a direct reference to a mutable internal field'),
('Immutable Field2','Making a field final ensures:','MCQ','EASY','OOP','Encapsulation','["It can only be read","Its reference cannot be reassigned after initialization","The object it points to cannot change","It is thread-safe"]','Its reference cannot be reassigned after initialization'),
('Data Hiding','Data hiding is achieved by:','MCQ','EASY','OOP','Encapsulation','["Making methods private","Making fields private and exposing via controlled methods","Using static methods","Using interfaces"]','Making fields private and exposing via controlled methods'),
('Encap in Real','Which real-world example best illustrates encapsulation?','MCQ','EASY','OOP','Encapsulation','["A public park","A car where internal engine details are hidden and you use a steering wheel","A library with open shelves","An open kitchen"]','A car where internal engine details are hidden and you use a steering wheel'),
('Cannot Change','Which scenario shows encapsulation preventing a bug?','MCQ','EASY','OOP','Encapsulation','["Calling methods from another class","A setter rejecting a negative age value","Using inheritance","Casting an object"]','A setter rejecting a negative age value'),
('Field Encap OOP','OOP field encapsulation ensures:','MCQ','EASY','OOP','Encapsulation','["Fields can be changed arbitrarily","Fields can only be changed through defined, controlled methods","Fields must be public","Fields are always static"]','Fields can only be changed through defined, controlled methods'),
('Access Breadth','From most restrictive to least restrictive, Java access modifiers are:','MCQ','EASY','OOP','Encapsulation','["public → protected → default → private","private → default → protected → public","protected → private → default → public","default → private → protected → public"]','private → default → protected → public'),
-- EASY CODING
('Private Field Declare','Declare a private String field named email inside a class.','CODING','EASY','OOP','Encapsulation',NULL,'private String email;'),
('Simple Getter','Write a public getter for private String field email.','CODING','EASY','OOP','Encapsulation',NULL,'public String getEmail() { return email; }'),
('Simple Setter','Write a public setter for private String field email.','CODING','EASY','OOP','Encapsulation',NULL,'public void setEmail(String email) { this.email = email; }'),
('Bool Getter','Write a public getter named isActive for a private boolean field active.','CODING','EASY','OOP','Encapsulation',NULL,'public boolean isActive() { return active; }'),
('Validated Setter','Write a setter for private int age that only assigns if age >= 0.','CODING','EASY','OOP','Encapsulation',NULL,'public void setAge(int age) { if(age >= 0) this.age = age; }'),

-- ================================================================
--  OOP / ENCAPSULATION  —  MEDIUM
-- ================================================================
('Defensive Copy','Returning a mutable Date field from a getter should return:','MCQ','MEDIUM','OOP','Encapsulation','["The original reference","A new Date with the same time value (defensive copy)","null","A string version"]','A new Date with the same time value (defensive copy)'),
('Law of Demeter','The Law of Demeter states a method should only call methods on:','MCQ','MEDIUM','OOP','Encapsulation','["Any object in the system","Its own object, parameters, fields, and locally created objects","Only static methods","Only objects passed via constructor"]','Its own object, parameters, fields, and locally created objects'),
('Tell Dont Ask','Tell, Don''t Ask principle means:','MCQ','MEDIUM','OOP','Encapsulation','["Tell the compiler the type","Ask objects for data, then decide for them","Tell objects what to do rather than asking for data to make decisions externally","Ask for permissions before calling methods"]','Tell objects what to do rather than asking for data to make decisions externally'),
('Package Private Use','Package-private classes are useful for:','MCQ','MEDIUM','OOP','Encapsulation','["Public APIs","Helper classes not part of a package''s public API","Global utilities","Abstract base classes"]','Helper classes not part of a package''s public API'),
('Record Encap','Java Records provide encapsulation by:','MCQ','MEDIUM','OOP','Encapsulation','["Making fields public mutable","Making fields private final with auto-generated accessors, equals, hashCode","Allowing arbitrary setters","Using reflection"]','Making fields private final with auto-generated accessors, equals, hashCode'),
('Sync Encap','Encapsulating mutable shared state with synchronized methods:','MCQ','MEDIUM','OOP','Encapsulation','["Slows down programs always","Hides thread-safety complexity from callers","Requires callers to synchronize manually","Prevents GC"]','Hides thread-safety complexity from callers'),
('Immutable Deep','A truly immutable class must:','MCQ','MEDIUM','OOP','Encapsulation','["Have no methods","Make a defensive copy of mutable objects passed in and returned","Use volatile fields","Have only static methods"]','Make a defensive copy of mutable objects passed in and returned'),
('Module JPMS','Java 9 modules (module-info.java) extend encapsulation by:','MCQ','MEDIUM','OOP','Encapsulation','["Making all classes private","Restricting which packages are exported and accessible outside the module","Adding new access modifiers","Preventing reflection always"]','Restricting which packages are exported and accessible outside the module'),
('Builder Encap','The Builder pattern encapsulates:','MCQ','MEDIUM','OOP','Encapsulation','["Execution logic","Object construction complexity and validates the object before building","Database queries","UI rendering"]','Object construction complexity and validates the object before building'),
('Encap Interface','Programming to an interface promotes encapsulation because:','MCQ','MEDIUM','OOP','Encapsulation','["Interfaces have no fields","Callers depend on the interface, not the concrete implementation — internals can change freely","Interfaces are immutable","Interfaces prevent subclassing"]','Callers depend on the interface, not the concrete implementation — internals can change freely'),
('Coupling','High coupling between classes means:','MCQ','MEDIUM','OOP','Encapsulation','["Good encapsulation","Classes are highly dependent on each other''s internal details — bad for maintainability","Better performance","Easier testing"]','Classes are highly dependent on each other''s internal details — bad for maintainability'),
('Copy Constructor Encap','A copy constructor in a mutable class ensures:','MCQ','MEDIUM','OOP','Encapsulation','["The copy shares the same mutable reference","The copy is a deep copy, preventing aliasing bugs","The copy is a shallow copy","The original cannot change"]','The copy is a deep copy, preventing aliasing bugs'),
('Cohesion','High cohesion means:','MCQ','MEDIUM','OOP','Encapsulation','["A class has many responsibilities","A class has a single, well-defined responsibility — strong encapsulation","Methods are long","Classes are coupled"]','A class has a single, well-defined responsibility — strong encapsulation'),
('Mutable Param','When a constructor receives a mutable List, proper encapsulation requires:','MCQ','MEDIUM','OOP','Encapsulation','["Storing the reference directly","Making a copy of the list and storing the copy","Converting to an array","Making the field public"]','Making a copy of the list and storing the copy'),
('Private Const','Having a private constructor in a class means:','MCQ','MEDIUM','OOP','Encapsulation','["No objects can be created","The class cannot be extended, and instantiation is controlled (e.g. Singleton, factory)","All methods must be static","The class is abstract"]','The class cannot be extended, and instantiation is controlled (e.g. Singleton, factory)'),
('Static Field Encap','A mutable public static field breaks encapsulation because:','MCQ','MEDIUM','OOP','Encapsulation','["Static fields are slow","Any class can modify it directly, bypassing any validation logic","Static fields cannot be final","Only one class can use it"]','Any class can modify it directly, bypassing any validation logic'),
('Accessor in Record','Accessing a field in a Java Record uses:','MCQ','MEDIUM','OOP','Encapsulation','["Getter via get prefix (getName())","Direct field access","Accessor method with same name as field (name())","Static method"]','Accessor method with same name as field (name())'),
('DTOvsEntity','DTO (Data Transfer Object) promotes encapsulation by:','MCQ','MEDIUM','OOP','Encapsulation','["Replacing all entities","Exposing only the data needed for a specific use case, hiding entity internals","Making all fields public","Using inheritance from Entity"]','Exposing only the data needed for a specific use case, hiding entity internals'),
('Encap Testing','Encapsulation can hinder unit testing because:','MCQ','MEDIUM','OOP','Encapsulation','["Private fields are untestable in principle","Private methods can only be tested indirectly through public APIs (which is actually preferred)","Getters are slower","Tests require reflection always"]','Private methods can only be tested indirectly through public APIs (which is actually preferred)'),
('Opaque Type','An opaque type hides its implementation by:','MCQ','MEDIUM','OOP','Encapsulation','["Using primitives","Exposing only an interface/abstract type to callers, hiding the concrete class","Making the class final","Using generics"]','Exposing only an interface/abstract type to callers, hiding the concrete class'),
-- MEDIUM CODING
('Defensive Copy Code','Write a getter for a private Date field birthDate that returns a defensive copy.','CODING','MEDIUM','OOP','Encapsulation',NULL,'public Date getBirthDate() { return new Date(birthDate.getTime()); }'),
('Immutable List Return','Write a getter for a private List<String> items that returns an unmodifiable view.','CODING','MEDIUM','OOP','Encapsulation',NULL,'public List<String> getItems() { return Collections.unmodifiableList(items); }'),
('Private Constructor','Write a private constructor for class Singleton with no body.','CODING','MEDIUM','OOP','Encapsulation',NULL,'private Singleton() {}'),
('Validate Age','Write a setter for int field age that throws IllegalArgumentException if age is negative.','CODING','MEDIUM','OOP','Encapsulation',NULL,'public void setAge(int age) { if(age < 0) throw new IllegalArgumentException("Age cannot be negative"); this.age = age; }'),
('Final Field Init','Write a constructor for class Point that initializes two final int fields x and y.','CODING','MEDIUM','OOP','Encapsulation',NULL,'public Point(int x, int y) { this.x = x; this.y = y; }'),

-- ================================================================
--  OOP / ENCAPSULATION  —  HARD
-- ================================================================
('JPMS Exports','In Java 9 module-info.java, exports com.example means:','MCQ','HARD','OOP','Encapsulation','["All packages are exported","Only com.example package is accessible to other modules","All public types in com.example become private","Nothing — exports are automatic"]','Only com.example package is accessible to other modules'),
('Encap Concurrency','Which class provides the best encapsulation of thread-safe mutable state?','MCQ','HARD','OOP','Encapsulation','["A class with public fields + external synchronization","A class with private fields + internally synchronized methods","A class with volatile fields","A class with final fields"]','A class with private fields + internally synchronized methods'),
('Value Object','A Value Object (DDD term) is characterized by:','MCQ','HARD','OOP','Encapsulation','["Having a mutable identity","Being immutable and defined by its attribute values, not identity","Having a database ID","Extending Entity"]','Being immutable and defined by its attribute values, not identity'),
('Encap Reflection','Java reflection can bypass encapsulation using:','MCQ','HARD','OOP','Encapsulation','["Only public APIs","field.setAccessible(true) — then private fields can be read/written","Proxy classes","Static methods only"]','field.setAccessible(true) — then private fields can be read/written'),
('Deep Immutability','Deep immutability requires:','MCQ','HARD','OOP','Encapsulation','["Only final fields","All referenced mutable objects to also be made immutable or defensively copied","Private setters","A record type"]','All referenced mutable objects to also be made immutable or defensively copied'),
('LoD Violation','a.getB().getC().doSomething() violates the Law of Demeter because:','MCQ','HARD','OOP','Encapsulation','["It has too many method calls","It traverses the object graph, coupling a to the internal structure of B and C","It breaks polymorphism","Methods should not return objects"]','It traverses the object graph, coupling a to the internal structure of B and C'),
('Module Qualified Exports','Qualified exports (exports com.pkg to other.module) in Java 9:','MCQ','HARD','OOP','Encapsulation','["Exports to all","Export only to specified modules — fine-grained encapsulation","Are deprecated","Require reflection"]','Export only to specified modules — fine-grained encapsulation'),
('Persistent Immutable','When building immutable collections that support efficient functional updates, Java uses:','MCQ','HARD','OOP','Encapsulation','["ArrayList copy","Structural sharing (persistent data structures) — sharing unmodified parts","Always copying the full collection","Arrays instead"]','Structural sharing (persistent data structures) — sharing unmodified parts'),
('sealed Encap','Sealed classes contribute to encapsulation by:','MCQ','HARD','OOP','Encapsulation','["Making classes abstract","Restricting which classes can extend a type, preventing unexpected external subclassing","Making all fields private","Preventing reflection"]','Restricting which classes can extend a type, preventing unexpected external subclassing'),
('SOLID SRP','Single Responsibility Principle and encapsulation relate because:','MCQ','HARD','OOP','Encapsulation','["They are unrelated","A class with one responsibility has a tighter, better-encapsulated boundary","SRP requires many classes","Encapsulation implies multiple responsibilities"]','A class with one responsibility has a tighter, better-encapsulated boundary'),
('Encap AOP','Aspect-Oriented Programming (AOP) can break encapsulation by:','MCQ','HARD','OOP','Encapsulation','["Adding methods","Weaving cross-cutting concerns into private implementation details at bytecode level","Removing methods","Adding interfaces"]','Weaving cross-cutting concerns into private implementation details at bytecode level'),
('Stack Encap','A Stack ADT encapsulates its internal array by:','MCQ','HARD','OOP','Encapsulation','["Exposing the array directly","Hiding the array and exposing only push, pop, peek, and isEmpty","Making the array public final","Using generics only"]','Hiding the array and exposing only push, pop, peek, and isEmpty'),
('open Module','In Java 9, open module opens ALL packages to reflection. This is less encapsulated than a normal module because:','MCQ','HARD','OOP','Encapsulation','["It is faster","Runtime reflection can access all packages, even non-exported ones","It restricts more","It has no effect"]','Runtime reflection can access all packages, even non-exported ones'),
('Abstract Type','Using abstract types (interfaces/abstract classes) in public APIs promotes encapsulation because:','MCQ','HARD','OOP','Encapsulation','["Abstract classes are faster","Concrete implementation details are hidden behind the abstraction boundary","It prevents polymorphism","It removes the need for tests"]','Concrete implementation details are hidden behind the abstraction boundary'),
('Encap Inheritance Break','Why does inheritance break encapsulation?','MCQ','HARD','OOP','Encapsulation','["It is always fine","Subclasses depend on parent internals; changes to parent can break subclasses","Inheritance removes access modifiers","Inheritance duplicates code"]','Subclasses depend on parent internals; changes to parent can break subclasses'),
('Composition Encap','Composition is preferred over inheritance for encapsulation because:','MCQ','HARD','OOP','Encapsulation','["Composition is faster","The composed object''s internals are fully hidden; the outer class is not affected by changes to the inner class","Composition allows multiple inheritance","Composition reduces code"]','The composed object''s internals are fully hidden; the outer class is not affected by changes to the inner class'),
('Visibility Grid','A member with protected access in class A can be accessed from:','MCQ','HARD','OOP','Encapsulation','["Anywhere","Only in A","A, same package, and subclasses of A (in any package)","A and subclasses only (not same package others)"]','A, same package, and subclasses of A (in any package)'),
('Encap by Contract','Design by Contract (pre/postconditions, invariants) relates to encapsulation by:','MCQ','HARD','OOP','Encapsulation','["Replacing access modifiers","Formally specifying what a class guarantees, strengthening the encapsulation boundary with verifiable rules","Removing getters","Requiring public fields"]','Formally specifying what a class guarantees, strengthening the encapsulation boundary with verifiable rules'),
('Visiblity Subclass','A subclass in a different package can access a parent''s protected member:','MCQ','HARD','OOP','Encapsulation','["Always","Only through a reference of the subclass type or its subtype, not through a parent-type reference","Never","Only if the member is also static"]','Only through a reference of the subclass type or its subtype, not through a parent-type reference'),
('Encap Final','Making a class final ensures encapsulation by:','MCQ','HARD','OOP','Encapsulation','["Removing all methods","Preventing subclasses from modifying or overriding the encapsulated behavior","Making fields private","Adding synchronization"]','Preventing subclasses from modifying or overriding the encapsulated behavior'),
-- HARD CODING
('Module Export','Write the module-info.java statement that exports package com.app.api only to module client.module.','CODING','HARD','OOP','Encapsulation',NULL,'exports com.app.api to client.module;'),
('Immutable Class','Write a complete immutable class Point with final int fields x and y, a constructor, and getters x() and y().','CODING','HARD','OOP','Encapsulation',NULL,'public final class Point { private final int x; private final int y; public Point(int x,int y){this.x=x;this.y=y;} public int x(){return x;} public int y(){return y;} }'),
('Accessible Field','Write the Java reflection code to make a private field named secret in class Config accessible and set it to 42 on object cfg.','CODING','HARD','OOP','Encapsulation',NULL,'Field f = Config.class.getDeclaredField("secret"); f.setAccessible(true); f.set(cfg, 42);'),
('Unmodifiable Map','Write a getter for a private Map<String,Integer> scores that returns an unmodifiable view.','CODING','HARD','OOP','Encapsulation',NULL,'public Map<String,Integer> getScores() { return Collections.unmodifiableMap(scores); }'),
('Record Declaration','Declare a Java Record named Coordinate with two int components x and y.','CODING','HARD','OOP','Encapsulation',NULL,'public record Coordinate(int x, int y) {}');

-- (DSA, OS, DBMS sections continue in seed_questions_v2_part2.sql)

-- ── Verification ───────────────────────────────────────────────────────────
SELECT prep_field, topic, difficulty, type, COUNT(*) AS question_count
FROM questions
GROUP BY prep_field, topic, difficulty, type
ORDER BY prep_field, topic, difficulty, type;
