-- ============================================================
--  GamePrep — Seed Script v2  PART 2
--  DSA: Arrays, Linked List, Stack, Queue, Tree, Graph
--  450 questions (6 topics x 3 diff x 25)
-- ============================================================

USE gameprep_db;

INSERT INTO questions (title, description, type, difficulty, prep_field, topic, options_json, correct_answer) VALUES

-- ================================================================
--  DSA / ARRAYS  —  EASY
-- ================================================================
('Array Access','What is the time complexity of accessing an element by index in an array?','MCQ','EASY','DSA','Arrays','["O(n)","O(log n)","O(1)","O(n^2)"]','O(1)'),
('Array Fixed','Arrays have a ___ size once allocated.','MCQ','EASY','DSA','Arrays','["dynamic","unlimited","fixed","unknown"]','fixed'),
('Array Index','Arrays in C++ are ___ indexed.','MCQ','EASY','DSA','Arrays','["1","0","2","-1"]','0'),
('Array Memory','Array elements are stored in ___ memory locations.','MCQ','EASY','DSA','Arrays','["random","linked","contiguous","non-contiguous"]','contiguous'),
('Array Search','Linear search on an unsorted array has time complexity:','MCQ','EASY','DSA','Arrays','["O(1)","O(log n)","O(n)","O(n log n)"]','O(n)'),
('Binary Search Pre','Binary search requires the array to be:','MCQ','EASY','DSA','Arrays','["Unsorted","Sorted","Circular","Linked"]','Sorted'),
('Binary Search Complexity','Binary search time complexity is:','MCQ','EASY','DSA','Arrays','["O(n)","O(n^2)","O(log n)","O(1)"]','O(log n)'),
('Array Insert End','Inserting at the end of an array (with space) is:','MCQ','EASY','DSA','Arrays','["O(n)","O(log n)","O(1)","O(n^2)"]','O(1)'),
('Array Insert Mid','Inserting in the middle of an array requires:','MCQ','EASY','DSA','Arrays','["No shift","Shifting elements — O(n)","A new array always","Sorting first"]','Shifting elements — O(n)'),
('Array Delete','Deleting from the middle of an array is:','MCQ','EASY','DSA','Arrays','["O(1)","O(log n)","O(n) due to shifting","O(n^2)"]','O(n) due to shifting'),
('C++ Vector','The C++ equivalent of a dynamic array is:','MCQ','EASY','DSA','Arrays','["list","deque","vector","set"]','vector'),
('Array vs LinkedList','Compared to a linked list, array provides:','MCQ','EASY','DSA','Arrays','["Faster insertion anywhere","Faster sequential access and O(1) random access","Less memory usage","Better cache miss rate"]','Faster sequential access and O(1) random access'),
('Array 2D','A 2D array of size m x n has how many total elements?','MCQ','EASY','DSA','Arrays','["m+n","m*n","2*m*n","m^n"]','m*n'),
('Array Type','All elements in a C++ array must be of:','MCQ','EASY','DSA','Arrays','["Different types","The same type","Pointer types only","Primitive types only"]','The same type'),
('Sort Bubble','Bubble Sort has worst-case complexity of:','MCQ','EASY','DSA','Arrays','["O(n)","O(n log n)","O(n^2)","O(log n)"]','O(n^2)'),
('Sort Merge','Merge Sort worst-case complexity is:','MCQ','EASY','DSA','Arrays','["O(n^2)","O(n log n)","O(n)","O(log n)"]','O(n log n)'),
('Sort Stable','Which sort is stable (preserves order of equal elements)?','MCQ','EASY','DSA','Arrays','["Quick Sort","Heap Sort","Merge Sort","Selection Sort"]','Merge Sort'),
('C++ Sort','C++ std::sort uses which underlying algorithm?','MCQ','EASY','DSA','Arrays','["Merge Sort","Bubble Sort","Introsort (hybrid quicksort + heapsort + insertion)","Radix Sort"]','Introsort (hybrid quicksort + heapsort + insertion)'),
('Array Pass','In C++, when you pass an array to a function it decays to:','MCQ','EASY','DSA','Arrays','["A copy of the array","A pointer to the first element","A vector","A reference to the array"]','A pointer to the first element'),
('Dynamic Array C++','To allocate a dynamic array of 10 ints in C++:','MCQ','EASY','DSA','Arrays','["int arr[10];","int arr = new int(10);","int* arr = new int[10];","vector arr(10);"]','int* arr = new int[10];'),
-- EASY CODING
('Declare Array','Write C++ code to declare and initialize an integer array arr with values 1,2,3,4,5.','CODING','EASY','DSA','Arrays',NULL,'int arr[] = {1, 2, 3, 4, 5};'),
('Array Size','Write C++ code to find the number of elements in array arr using sizeof.','CODING','EASY','DSA','Arrays',NULL,'int n = sizeof(arr) / sizeof(arr[0]);'),
('Print Array','Write C++ for-loop to print all elements of array arr of size n.','CODING','EASY','DSA','Arrays',NULL,'for(int i=0;i<n;i++) cout << arr[i] << " ";'),
('Reverse Array','Write C++ code using two pointers l=0 and r=n-1 to swap arr[l] and arr[r] once.','CODING','EASY','DSA','Arrays',NULL,'swap(arr[l], arr[r]);'),
('Std Sort','Write C++ statement to sort array arr of size n in ascending order using std::sort.','CODING','EASY','DSA','Arrays',NULL,'sort(arr, arr + n);'),

-- ================================================================
--  DSA / ARRAYS  —  MEDIUM
-- ================================================================
('Two Pointer','Two-pointer technique is best used on:','MCQ','MEDIUM','DSA','Arrays','["Unsorted linked lists","Sorted arrays for problems like pair-sum, container with most water","Binary trees","Hash maps"]','Sorted arrays for problems like pair-sum, container with most water'),
('Prefix Sum','Prefix sum array allows range sum queries in:','MCQ','MEDIUM','DSA','Arrays','["O(n) per query","O(log n) per query","O(1) per query after O(n) preprocessing","O(n^2) per query"]','O(1) per query after O(n) preprocessing'),
('Sliding Window','Sliding window technique solves subarray problems in:','MCQ','MEDIUM','DSA','Arrays','["O(n^2)","O(n) — by expanding/shrinking a window","O(log n)","O(n log n)"]','O(n) — by expanding/shrinking a window'),
('Kadane Algo','Kadane''s algorithm finds the maximum subarray sum in:','MCQ','MEDIUM','DSA','Arrays','["O(n^2)","O(n log n)","O(n)","O(log n)"]','O(n)'),
('Dutch Flag','The Dutch National Flag algorithm sorts an array of 0s,1s,2s in:','MCQ','MEDIUM','DSA','Arrays','["O(n^2) time, O(n) space","O(n) time, O(1) space","O(n log n) time, O(1) space","O(n) time, O(n) space"]','O(n) time, O(1) space'),
('Quicksort Pivot','Quick Sort performance heavily depends on:','MCQ','MEDIUM','DSA','Arrays','["Array size only","Choice of pivot — bad pivot leads to O(n^2) worst case","Number of duplicates","Memory available"]','Choice of pivot — bad pivot leads to O(n^2) worst case'),
('Counting Sort','Counting Sort is efficient when:','MCQ','MEDIUM','DSA','Arrays','["Elements are large","Range of values (k) is small relative to n — O(n+k)","Array is already sorted","Elements are floating point"]','Range of values (k) is small relative to n — O(n+k)'),
('Merge Sort Space','Merge Sort requires ___ extra space.','MCQ','MEDIUM','DSA','Arrays','["O(1)","O(log n)","O(n)","O(n^2)"]','O(n)'),
('Rotate Array','Rotating an array by k positions can be done in O(n) time O(1) space using:','MCQ','MEDIUM','DSA','Arrays','["Two pointers","Three reversals","Binary search","Merge sort"]','Three reversals'),
('Max Subarray Brute','Brute force maximum subarray sum checks all subarrays in:','MCQ','MEDIUM','DSA','Arrays','["O(n)","O(n log n)","O(n^2)","O(n^3)"]','O(n^2)'),
('2Sum Sorted','Two Sum on a sorted array using two pointers is:','MCQ','MEDIUM','DSA','Arrays','["O(n^2)","O(n log n)","O(n)","O(log n)"]','O(n)'),
('3Sum','3Sum problem best approach is:','MCQ','MEDIUM','DSA','Arrays','["Brute O(n^3)","Sort + two pointer O(n^2)","Hash map O(n)","Binary search O(n log n)"]','Sort + two pointer O(n^2)'),
('Product Except Self','Product of array except self without division in O(n) uses:','MCQ','MEDIUM','DSA','Arrays','["One pass","Left prefix and right suffix product arrays","Sorting","Kadane''s algorithm"]','Left prefix and right suffix product arrays'),
('Find Missing','Finding missing number 1..n in array of n-1 elements: best approach?','MCQ','MEDIUM','DSA','Arrays','["Sort and scan","XOR of all numbers with 1..n","Quadratic search","Linked list"]','XOR of all numbers with 1..n'),
('Move Zeros','Move all zeros to end of array while maintaining order of non-zeros in O(n):','MCQ','MEDIUM','DSA','Arrays','["Sort descending","Two pointers: one for write position, one for scan","Counting sort","Extra array"]','Two pointers: one for write position, one for scan'),
('Merge Sorted','Merging two sorted arrays of size m and n takes:','MCQ','MEDIUM','DSA','Arrays','["O(m+n)","O(m*n)","O(log(m+n))","O(m)"]','O(m+n)'),
('InPlace Sort','Which sort does NOT sort in-place (requires O(n) extra space)?','MCQ','MEDIUM','DSA','Arrays','["Quick Sort","Heap Sort","Insertion Sort","Merge Sort"]','Merge Sort'),
('Intersection','Finding intersection of two sorted arrays of size m and n efficiently:','MCQ','MEDIUM','DSA','Arrays','["O(m*n) brute force","O(m+n) two pointer approach","O(log n) binary search","O(m*log n) mixed"]','O(m+n) two pointer approach'),
('Stocks Problem','Best time to buy and sell stock (one transaction) optimal time:','MCQ','MEDIUM','DSA','Arrays','["O(n^2)","O(n) — track min so far and max profit","O(log n)","O(n log n)"]','O(n) — track min so far and max profit'),
('Majority Element','Boyer-Moore Voting Algorithm finds the majority element (>n/2) in:','MCQ','MEDIUM','DSA','Arrays','["O(n^2) time, O(n) space","O(n) time, O(1) space","O(n log n) time, O(1) space","O(n) time, O(n) space"]','O(n) time, O(1) space'),
-- MEDIUM CODING
('Kadane Code','Write the C++ Kadane''s algorithm to find max subarray sum of vector<int> a, returning int.','CODING','MEDIUM','DSA','Arrays',NULL,'int kadane(vector<int>& a){int best=a[0],cur=a[0];for(int i=1;i<a.size();i++){cur=max(a[i],cur+a[i]);best=max(best,cur);}return best;}'),
('Prefix Sum Build','Write C++ code to build prefix sum array pre[] from int arr[] of size n (pre[0]=arr[0]).','CODING','MEDIUM','DSA','Arrays',NULL,'for(int i=1;i<n;i++) pre[i]=pre[i-1]+arr[i];'),
('Two Pointer Sum','Write the C++ two-pointer approach body to find if sorted array arr[] of size n has a pair summing to target. Variables l=0, r=n-1 already declared.','CODING','MEDIUM','DSA','Arrays',NULL,'while(l<r){int s=arr[l]+arr[r];if(s==target)return true;else if(s<target)l++;else r--;}return false;'),
('Rotate Three Reverse','Write C++ code to rotate array arr of size n left by k using three reversals.','CODING','MEDIUM','DSA','Arrays',NULL,'k%=n;reverse(arr,arr+k);reverse(arr+k,arr+n);reverse(arr,arr+n);'),
('Move Zeros Code','Write C++ code to move all zeros to end of array arr of size n maintaining order. Use writePos variable.','CODING','MEDIUM','DSA','Arrays',NULL,'int writePos=0;for(int i=0;i<n;i++)if(arr[i]!=0)arr[writePos++]=arr[i];while(writePos<n)arr[writePos++]=0;'),

-- ================================================================
--  DSA / ARRAYS  —  HARD
-- ================================================================
('Trapping Rain','Trapping Rain Water problem: optimal approach is:','MCQ','HARD','DSA','Arrays','["O(n^2) brute","O(n) two pointer with leftMax/rightMax arrays","O(n) monotonic stack","Both two pointer and monotonic stack are O(n)"]','Both two pointer and monotonic stack are O(n)'),
('Largest Rectangle','Largest Rectangle in Histogram optimal complexity:','MCQ','HARD','DSA','Arrays','["O(n^2)","O(n log n)","O(n) using monotonic stack","O(n^2) minimum"]','O(n) using monotonic stack'),
('Median Two Sorted','Median of two sorted arrays of size m and n: optimal complexity:','MCQ','HARD','DSA','Arrays','["O(m+n)","O(log(min(m,n))) using binary search on smaller array","O(m*n)","O(n log n) after merge"]','O(log(min(m,n))) using binary search on smaller array'),
('Shortest Subarray Sum K','Shortest subarray with sum at least K (may have negatives): solved optimally using:','MCQ','HARD','DSA','Arrays','["Sliding window only","Monotonic deque with prefix sums — O(n)","Sorting","Binary search"]','Monotonic deque with prefix sums — O(n)'),
('Count Inversions','Counting inversions in an array (pairs i<j where arr[i]>arr[j]) optimally:','MCQ','HARD','DSA','Arrays','["O(n^2) brute","O(n log n) using modified merge sort","O(n) Kadane adaptation","O(n log n) with BIT/Fenwick tree"]','O(n log n) using modified merge sort'),
('Sparse Table','A Sparse Table enables range minimum/maximum queries in:','MCQ','HARD','DSA','Arrays','["O(n) build, O(1) query","O(n log n) build, O(1) query","O(n^2) build, O(1) query","O(n) build, O(log n) query"]','O(n log n) build, O(1) query'),
('Circular Subarray Max','Maximum sum circular subarray can be found by:','MCQ','HARD','DSA','Arrays','["Running Kadane twice","max(standard_max_subarray, total_sum - min_subarray_sum)","Rotating and running Kadane","Sorting first"]','max(standard_max_subarray, total_sum - min_subarray_sum)'),
('Merge K Sorted Arrays','Merging K sorted arrays of total N elements using a min-heap:','MCQ','HARD','DSA','Arrays','["O(NK)","O(N log K)","O(N log N)","O(K^2)"]','O(N log K)'),
('Wiggle Sort','Wiggle Sort II arranges array such that a[0]<a[1]>a[2]<a[3]. Can be done in:','MCQ','HARD','DSA','Arrays','["O(n^2)","O(n log n) with sort","O(n) average using nth_element + virtual indexing","O(n) always with counting sort"]','O(n) average using nth_element + virtual indexing'),
('Jump Game II','Minimum jumps to reach end of array (Jump Game II) optimal:','MCQ','HARD','DSA','Arrays','["O(n^2) DP","O(n) greedy: track current reach and next reach","O(n log n) binary search","O(n) BFS"]','O(n) greedy: track current reach and next reach'),
('Max Sum No Adjacent','Maximum sum of non-adjacent elements: algorithm class?','MCQ','HARD','DSA','Arrays','["Greedy","Dynamic programming: dp[i]=max(dp[i-1], dp[i-2]+a[i])","Divide and conquer","Binary search"]','Dynamic programming: dp[i]=max(dp[i-1], dp[i-2]+a[i])'),
('Longest Consec','Longest consecutive sequence in unsorted array in O(n): uses','MCQ','HARD','DSA','Arrays','["Sorting","Hash set: for each num check if num-1 exists in set","Kadane","BFS"]','Hash set: for each num check if num-1 exists in set'),
('Subarray Equal','Number of subarrays with sum equal to K: optimal approach:','MCQ','HARD','DSA','Arrays','["O(n^2) two loops","O(n) prefix sum + hash map counting frequencies","O(n log n)","O(n^3)"]','O(n) prefix sum + hash map counting frequencies'),
('Next Greater Mon Stack','Next Greater Element for all array elements in O(n) uses:','MCQ','HARD','DSA','Arrays','["Sorting","Two pointer","Monotonic decreasing stack","Binary search"]','Monotonic decreasing stack'),
('Median Sliding Window','Sliding window median of size k uses:','MCQ','HARD','DSA','Arrays','["Sorting window each step O(nk log k)","Two heaps (max-heap + min-heap) O(n log k)","Binary search O(n log k)","Merge sort adaptation"]','Two heaps (max-heap + min-heap) O(n log k)'),
('Power Set','Generating all subsets of n elements: there are ___ subsets.','MCQ','HARD','DSA','Arrays','["n!","n^2","2^n","n*2"]','2^n'),
('Smallest Window','Smallest window in S containing all characters of T: approach?','MCQ','HARD','DSA','Arrays','["O(n^2) brute","O(n) sliding window with frequency map","O(n log n)","O(n*|T|)"]','O(n) sliding window with frequency map'),
('XOR Swap','XOR swap a and b without temp: correct sequence?','MCQ','HARD','DSA','Arrays','["a=a^b; b=b^a; a=a^b;","a=a+b; b=a-b; a=a-b;","a=b; b=a;","a^=b; a^=b; b^=a;"]','a=a^b; b=b^a; a=a^b;'),
('Bit Manipulation Subset','Enumerating all subsets using bitmask for n items iterates from:','MCQ','HARD','DSA','Arrays','["0 to n","0 to 2^n - 1","1 to n!","0 to n^2"]','0 to 2^n - 1'),
('Sqrt Decomp','Square root decomposition for range queries divides array into blocks of size:','MCQ','HARD','DSA','Arrays','["log n","sqrt(n)","n/2","2"]','sqrt(n)'),
-- HARD CODING
('Largest Rectangle Histogram','Write the C++ monotonic stack solution for Largest Rectangle in Histogram. Function signature: int largestRect(vector<int>& h).','CODING','HARD','DSA','Arrays',NULL,'int largestRect(vector<int>& h){int n=h.size(),res=0;stack<int> st;for(int i=0;i<=n;i++){int cur=(i==n)?0:h[i];while(!st.empty()&&h[st.top()]>cur){int height=h[st.top()];st.pop();int width=st.empty()?i:i-st.top()-1;res=max(res,height*width);}st.push(i);}return res;}'),
('Trapping Rain Code','Write C++ two-pointer solution for Trapping Rain Water. Signature: int trap(vector<int>& h).','CODING','HARD','DSA','Arrays',NULL,'int trap(vector<int>& h){int l=0,r=h.size()-1,lm=0,rm=0,res=0;while(l<r){if(h[l]<h[r]){lm=max(lm,h[l]);res+=lm-h[l++];}else{rm=max(rm,h[r]);res+=rm-h[r--];}}return res;}'),
('Subarray Sum K','Write C++ O(n) solution to count subarrays with sum K using prefix sum + unordered_map. Signature: int subarraySum(vector<int>& a,int k).','CODING','HARD','DSA','Arrays',NULL,'int subarraySum(vector<int>& a,int k){unordered_map<int,int> mp;mp[0]=1;int pre=0,cnt=0;for(int x:a){pre+=x;cnt+=mp[pre-k];mp[pre]++;}return cnt;}'),
('Longest Consecutive','Write C++ O(n) solution for Longest Consecutive Sequence using unordered_set.','CODING','HARD','DSA','Arrays',NULL,'int longestConsecutive(vector<int>& a){unordered_set<int> s(a.begin(),a.end());int res=0;for(int n:s)if(!s.count(n-1)){int cur=n,len=1;while(s.count(cur+1)){cur++;len++;}res=max(res,len);}return res;}'),
('Next Greater','Write C++ O(n) Next Greater Element solution using monotonic stack. Returns vector<int> nge for input vector<int> a.','CODING','HARD','DSA','Arrays',NULL,'vector<int> nextGreater(vector<int>& a){int n=a.size();vector<int> res(n,-1);stack<int> st;for(int i=0;i<n;i++){while(!st.empty()&&a[st.top()]<a[i]){res[st.top()]=a[i];st.pop();}st.push(i);}return res;}'),

-- ================================================================
--  DSA / LINKED LIST  —  EASY
-- ================================================================
('LL Node','A singly linked list node contains:','MCQ','EASY','DSA','Linked List','["Only data","Data and pointer to previous","Data and pointer to next","Two data fields"]','Data and pointer to next'),
('LL Head','The first node of a linked list is called the:','MCQ','EASY','DSA','Linked List','["Tail","Sentinel","Head","Root"]','Head'),
('LL Access Time','Accessing the nth node of a singly linked list is:','MCQ','EASY','DSA','Linked List','["O(1)","O(log n)","O(n)","O(n^2)"]','O(n)'),
('LL Insert Head','Inserting at the head of a singly linked list is:','MCQ','EASY','DSA','Linked List','["O(n)","O(log n)","O(1)","O(n^2)"]','O(1)'),
('LL Doubly','A doubly linked list node has:','MCQ','EASY','DSA','Linked List','["Only a next pointer","Only a prev pointer","Both prev and next pointers","Three pointers"]','Both prev and next pointers'),
('LL vs Array','Linked list advantage over array:','MCQ','EASY','DSA','Linked List','["O(1) random access","No wasted memory","Dynamic size with O(1) insert at head/known position","Better cache performance"]','Dynamic size with O(1) insert at head/known position'),
('LL Last Node','The last node of a singly linked list points next to:','MCQ','EASY','DSA','Linked List','["The first node","Itself","null/nullptr","An undefined address"]','null/nullptr'),
('LL Circular','A circular linked list differs from a regular one in that:','MCQ','EASY','DSA','Linked List','["It has no head","The last node points to the head instead of null","Nodes have three pointers","It cannot be traversed"]','The last node points to the head instead of null'),
('LL Delete Head','Deleting the head node of a singly linked list is:','MCQ','EASY','DSA','Linked List','["O(n)","O(1)","O(log n)","O(n^2)"]','O(1)'),
('LL Search','Searching for a value in an unsorted linked list is:','MCQ','EASY','DSA','Linked List','["O(1)","O(log n)","O(n)","O(n log n)"]','O(n)'),
('LL Extra Memory','A linked list uses more memory than an array because:','MCQ','EASY','DSA','Linked List','["Nodes are larger","Each node stores a data field plus one or more pointer fields","Linked lists duplicate data","Random access requires extra memory"]','Each node stores a data field plus one or more pointer fields'),
('LL Size','Finding the size (length) of a singly linked list requires:','MCQ','EASY','DSA','Linked List','["O(1)","O(log n)","O(n) traversal","O(n^2)"]','O(n) traversal'),
('LL Insert After','Inserting a node after a given node in a linked list is:','MCQ','EASY','DSA','Linked List','["O(n)","O(1) given the reference to that node","O(log n)","O(n^2)"]','O(1) given the reference to that node'),
('LL C++ Null','In C++, the null pointer is represented as:','MCQ','EASY','DSA','Linked List','["nil","null","nullptr","0 or nullptr (both valid)"]','0 or nullptr (both valid)'),
('LL Singly vs Doubly Memory','Doubly linked list vs singly linked list: memory per node?','MCQ','EASY','DSA','Linked List','["Same","Doubly uses more — extra prev pointer","Singly uses more — next pointer is larger","No difference in practice"]','Doubly uses more — extra prev pointer'),
('LL Stack Impl','A stack can be implemented using a linked list with O(1) push and pop by:','MCQ','EASY','DSA','Linked List','["Inserting and removing at tail","Inserting and removing at head","Keeping sorted order","Using a doubly linked list only"]','Inserting and removing at head'),
('LL Queue Impl','A queue can be implemented efficiently using a linked list by:','MCQ','EASY','DSA','Linked List','["Inserting at head, removing at tail","Inserting at tail, removing at head (enqueue at tail, dequeue at head)","Using circular references","Sorting on insert"]','Inserting at tail, removing at head (enqueue at tail, dequeue at head)'),
('LL No Random','Linked lists do NOT support:','MCQ','EASY','DSA','Linked List','["Insertion","Deletion","O(1) random access by index","Traversal"]','O(1) random access by index'),
('LL Reverse Type','Reversing a singly linked list is possible:','MCQ','EASY','DSA','Linked List','["Only recursively","Only iteratively","Both iteratively and recursively","Only with extra space"]','Both iteratively and recursively'),
('LL Middle','Finding the middle of a linked list efficiently uses:','MCQ','EASY','DSA','Linked List','["Counting then traversing half","Slow (1 step) and fast (2 steps) pointers — stop when fast reaches end","Sorting","A stack"]','Slow (1 step) and fast (2 steps) pointers — stop when fast reaches end'),
-- EASY CODING
('LL Node Struct','Write a C++ struct Node for a singly linked list with int data and Node* next, initialized to nullptr.','CODING','EASY','DSA','Linked List',NULL,'struct Node { int data; Node* next; Node(int d):data(d),next(nullptr){} };'),
('LL Insert Head Code','Write C++ code to insert new Node(5) at head of linked list (head pointer already declared).','CODING','EASY','DSA','Linked List',NULL,'Node* temp = new Node(5); temp->next = head; head = temp;'),
('LL Traverse','Write C++ while-loop to print all data values of a linked list starting at head.','CODING','EASY','DSA','Linked List',NULL,'Node* cur=head; while(cur){cout<<cur->data<<" ";cur=cur->next;}'),
('LL Delete Head','Write C++ code to delete the head node of a linked list (head is not null).','CODING','EASY','DSA','Linked List',NULL,'Node* temp=head; head=head->next; delete temp;'),
('LL Find Middle','Write C++ code to find the middle node of a linked list using slow/fast pointers.','CODING','EASY','DSA','Linked List',NULL,'Node* slow=head,*fast=head; while(fast&&fast->next){slow=slow->next;fast=fast->next->next;}'),

-- ================================================================
--  DSA / LINKED LIST  —  MEDIUM
-- ================================================================
('Floyd Detect','Floyd''s cycle detection uses pointers moving at speeds:','MCQ','MEDIUM','DSA','Linked List','["1 and 3","1 and 2 (tortoise and hare)","2 and 4","Equal speeds"]','1 and 2 (tortoise and hare)'),
('Floyd Space','Floyd''s cycle detection uses:','MCQ','MEDIUM','DSA','Linked List','["O(n) extra space","O(log n) extra space","O(1) extra space","O(n^2) extra space"]','O(1) extra space'),
('Reverse LL Complexity','Iteratively reversing a singly linked list: complexity?','MCQ','MEDIUM','DSA','Linked List','["O(n) time, O(n) space","O(n) time, O(1) space","O(log n) time, O(1) space","O(n^2) time, O(1) space"]','O(n) time, O(1) space'),
('Cycle Start','After detecting a cycle with Floyd''s, finding the cycle start requires:','MCQ','MEDIUM','DSA','Linked List','["One more pass with fast pointer","Reset one pointer to head, move both one step at a time until they meet","Use a hash set","Sort the list"]','Reset one pointer to head, move both one step at a time until they meet'),
('Merge Sorted LL','Merging two sorted linked lists of m and n nodes: complexity?','MCQ','MEDIUM','DSA','Linked List','["O((m+n)^2)","O(m+n)","O(m*n)","O(log(m+n))"]','O(m+n)'),
('Palindrome LL','Checking if a linked list is a palindrome in O(n) O(1) space:','MCQ','MEDIUM','DSA','Linked List','["Use a stack","Find middle, reverse second half, compare with first half","Sort and compare","Convert to array"]','Find middle, reverse second half, compare with first half'),
('Kth From End','Finding the kth node from the end of a linked list in one pass:','MCQ','MEDIUM','DSA','Linked List','["Sort then index","Use two pointers k nodes apart; advance both until fast reaches end","Recurse k times","Use a stack"]','Use two pointers k nodes apart; advance both until fast reaches end'),
('Remove Nth End','Remove nth node from end in one pass: technique?','MCQ','MEDIUM','DSA','Linked List','["Two passes","Two pointer: advance one pointer n steps ahead","Recursion","Stack"]','Two pointer: advance one pointer n steps ahead'),
('Intersection LL','Finding intersection node of two linked lists efficiently:','MCQ','MEDIUM','DSA','Linked List','["O(m*n) brute force","O(m+n) — traverse both lists; when one reaches end, redirect to head of the other","Sort both","Stack approach"]','O(m+n) — traverse both lists; when one reaches end, redirect to head of the other'),
('Clone LL Random','Cloning a linked list with a random pointer in O(n) O(1) space:','MCQ','MEDIUM','DSA','Linked List','["Use a hash map","Interleave cloned nodes with originals, fix randoms, then separate","Sort by random pointers","Two passes with recursion"]','Interleave cloned nodes with originals, fix randoms, then separate'),
('Flatten Mult Level','Flattening a multilevel doubly linked list (child pointers) in O(n) uses:','MCQ','MEDIUM','DSA','Linked List','["BFS","DFS/recursion or iterative stack to handle child lists","Sorting","Two pointers"]','DFS/recursion or iterative stack to handle child lists'),
('LRU Cache LL','LRU Cache uses a doubly linked list + hash map for:','MCQ','MEDIUM','DSA','Linked List','["O(n) get and put","O(1) get and put","O(log n) get and put","O(n log n) get and put"]','O(1) get and put'),
('Partition LL','Partitioning a linked list around value x (like quicksort pivot) in O(n):','MCQ','MEDIUM','DSA','Linked List','["Requires extra list","Two dummy heads; collect smaller and larger nodes, then link","Sort first","Use recursion"]','Two dummy heads; collect smaller and larger nodes, then link'),
('LL Reorder','Reorder list L0→Ln→L1→Ln-1... in O(n) O(1) space:','MCQ','MEDIUM','DSA','Linked List','["Sort then merge","Find middle, reverse second half, merge alternately","Use stack","Use deque"]','Find middle, reverse second half, merge alternately'),
('Josephus LL','Josephus problem can be solved with a circular linked list by:','MCQ','MEDIUM','DSA','Linked List','["Sorting","Simulating elimination by traversing k nodes and removing","Binary search","DFS"]','Simulating elimination by traversing k nodes and removing'),
('LL Cycle Length','Once a cycle is detected, finding cycle length from meeting point:','MCQ','MEDIUM','DSA','Linked List','["Restart Floyd''s","Keep one pointer fixed, move the other until it returns — count steps","Use a hash set","Use slow pointer only"]','Keep one pointer fixed, move the other until it returns — count steps'),
('Delete Without Head','Deleting a node from a linked list when only the node reference is given (not head):','MCQ','MEDIUM','DSA','Linked List','["Cannot be done","Copy next node''s data to current, point current''s next to next->next","Traverse from head to find previous","Reverse the list"]','Copy next node''s data to current, point current''s next to next->next'),
('LL Sort','Sorting a linked list: most efficient comparison-based sort is:','MCQ','MEDIUM','DSA','Linked List','["Quick Sort — no random access so slow","Bubble Sort — simple","Merge Sort — O(n log n), works well with LL","Heap Sort — needs array"]','Merge Sort — O(n log n), works well with LL'),
('Odd Even LL','Odd-Even linked list (group all odd-position then even-position nodes) in O(n):','MCQ','MEDIUM','DSA','Linked List','["Sort by index","Two pointer: odd and even heads, weave them","Stack","Recursion"]','Two pointer: odd and even heads, weave them'),
('Swap Pairs','Swapping pairs of adjacent nodes in a linked list iteratively in O(n):','MCQ','MEDIUM','DSA','Linked List','["One pointer","Use prev, first, second pointers to swap every two nodes","Stack","Recursion only"]','Use prev, first, second pointers to swap every two nodes'),
-- MEDIUM CODING
('Floyd Detect Code','Write C++ Floyd''s cycle detection. Signature: bool hasCycle(Node* head).','CODING','MEDIUM','DSA','Linked List',NULL,'bool hasCycle(Node* head){Node* s=head,*f=head;while(f&&f->next){s=s->next;f=f->next->next;if(s==f)return true;}return false;}'),
('Reverse LL Code','Write C++ iterative reversal of linked list. Signature: Node* reverse(Node* head).','CODING','MEDIUM','DSA','Linked List',NULL,'Node* reverse(Node* head){Node* prev=nullptr,*cur=head,*nxt;while(cur){nxt=cur->next;cur->next=prev;prev=cur;cur=nxt;}return prev;}'),
('Merge Two Sorted LL','Write C++ merge of two sorted linked lists. Signature: Node* mergeSorted(Node* a, Node* b).','CODING','MEDIUM','DSA','Linked List',NULL,'Node* mergeSorted(Node* a,Node* b){if(!a)return b;if(!b)return a;if(a->data<=b->data){a->next=mergeSorted(a->next,b);return a;}b->next=mergeSorted(a,b->next);return b;}'),
('Middle LL Code','Write C++ to find the middle node of a linked list using slow/fast pointers. Signature: Node* findMiddle(Node* head).','CODING','MEDIUM','DSA','Linked List',NULL,'Node* findMiddle(Node* head){Node* slow=head,*fast=head;while(fast&&fast->next){slow=slow->next;fast=fast->next->next;}return slow;}'),
('Kth From End Code','Write C++ to find kth node from end. Use two pointers. Signature: Node* kthFromEnd(Node* head, int k).','CODING','MEDIUM','DSA','Linked List',NULL,'Node* kthFromEnd(Node* head,int k){Node* a=head,*b=head;for(int i=0;i<k;i++)a=a->next;while(a){a=a->next;b=b->next;}return b;}'),

-- ================================================================
--  DSA / LINKED LIST  —  HARD
-- ================================================================
('Skip List O','Skip List provides expected time for search, insert, delete of:','MCQ','HARD','DSA','Linked List','["O(1)","O(n)","O(log n)","O(n log n)"]','O(log n)'),
('XOR LL','XOR Linked List stores in each node:','MCQ','HARD','DSA','Linked List','["prev XOR next pointer","Sum of addresses","Only next","Random bit"]','prev XOR next pointer'),
('LRU Eviction','In an LRU Cache using DLL+hashmap, when capacity is full and a new key is inserted:','MCQ','HARD','DSA','Linked List','["Remove head (oldest inserted)","Remove tail (least recently used in DLL where tail is LRU)","Remove random node","Evict the smallest key"]','Remove tail (least recently used in DLL where tail is LRU)'),
('Merge K Sorted LL','Merging K sorted linked lists of total N nodes using min-heap: complexity?','MCQ','HARD','DSA','Linked List','["O(NK)","O(N log K)","O(N^2)","O(K log N)"]','O(N log K)'),
('Clone Random LL','Cloning a linked list with random pointers optimally in O(n) O(1) extra space uses:','MCQ','HARD','DSA','Linked List','["HashMap of original to clone","Interleaved cloning: insert each clone after original, fix randoms, then detach","Recursion","BFS"]','Interleaved cloning: insert each clone after original, fix randoms, then detach'),
('Reverse K Group','Reverse nodes in K-group in a linked list, leaving remaining group as-is, in O(n):','MCQ','HARD','DSA','Linked List','["Recursion only","Iteratively process groups of K, reversing each group and reconnecting","Sort each group","Use stack per group O(n) space"]','Iteratively process groups of K, reversing each group and reconnecting'),
('Flatten DLL','Flattening multilevel DLL where each node may have a child list: time complexity?','MCQ','HARD','DSA','Linked List','["O(n^2)","O(n) — process each node exactly once with iterative stack","O(n log n)","O(n^2) worst case when deeply nested"]','O(n) — process each node exactly once with iterative stack'),
('Persistent LL','A persistent (immutable) linked list supports functional updates by:','MCQ','HARD','DSA','Linked List','["Copying the entire list","Path copying — creating new nodes on the changed path while sharing the unchanged suffix","Using XOR nodes","Storing all versions in a 2D array"]','Path copying — creating new nodes on the changed path while sharing the unchanged suffix'),
('Unroll LL','Unrolled Linked List stores:','MCQ','HARD','DSA','Linked List','["One element per node","A fixed-size array of elements per node — improves cache performance","Sorted sublists","Pointers only"]','A fixed-size array of elements per node — improves cache performance'),
('Sort LL MergeSort Why','Merge sort is preferred over quicksort for linked lists because:','MCQ','HARD','DSA','Linked List','["Merge sort is always faster","Linked lists lack O(1) random access making quicksort''s partition inefficient; merge sort needs only sequential access","Quicksort has worse complexity","Merge sort uses O(1) space for linked lists"]','Linked lists lack O(1) random access making quicksort''s partition inefficient; merge sort needs only sequential access'),
('Two Sum LL','Two Sum on a sorted doubly linked list uses:','MCQ','HARD','DSA','Linked List','["Hash map","Two pointers: one at head, one at tail — O(n) O(1)","Sort then hash","Binary search on each element"]','Two pointers: one at head, one at tail — O(n) O(1)'),
('Cycle Length','Given a linked list with a cycle, find the cycle length in O(n) O(1):','MCQ','HARD','DSA','Linked List','["Use Floyd''s, then count by traversing from meeting point once around","Hash set","Count nodes twice","Use fast pointer only"]','Use Floyd''s, then count by traversing from meeting point once around'),
('Median LL','Finding the median of a sorted doubly linked list of n nodes in O(1) (if size known):','MCQ','HARD','DSA','Linked List','["Always O(n)","O(1) by simultaneously moving forward from head and backward from tail until meeting","O(log n) skip list","O(n/2) by advancing from head to n/2"]','O(n/2) by advancing from head to n/2'),
('LL Quicksort','Implementing quicksort on a singly linked list without random access:','MCQ','HARD','DSA','Linked List','["Impossible","Partition by rearranging node values (not pointers) then recurse — O(n log n) average","Use array conversion","Use merge sort instead always"]','Partition by rearranging node values (not pointers) then recurse — O(n log n) average'),
('Add Numbers LL','Adding two numbers represented as linked lists (digits in reverse): result?','MCQ','HARD','DSA','Linked List','["Requires conversion to int","Traverse both simultaneously, carry the remainder — O(max(m,n))","O(m*n)","Impossible without extra space"]','Traverse both simultaneously, carry the remainder — O(max(m,n))'),
('Max Twin Sum','Maximum twin sum in a linked list of even length: optimal O(n) O(1) space:','MCQ','HARD','DSA','Linked List','["Sort then pair","Find middle, reverse second half, walk both halves comparing sums","Stack","Hash map"]','Find middle, reverse second half, walk both halves comparing sums'),
('Self Organize LL','A self-organizing list heuristic (move-to-front) has amortized O(1) for:','MCQ','HARD','DSA','Linked List','["All operations","Frequently accessed elements — reduces average access time","Never","Sorted access patterns only"]','Frequently accessed elements — reduces average access time'),
('DLL vs SLL Delete','Deleting a node given only its pointer: possible in O(1) for:','MCQ','HARD','DSA','Linked List','["Both SLL and DLL","DLL — prev pointer allows direct unlinking; SLL requires prev to be found or trick","Neither","Only for head node"]','DLL — prev pointer allows direct unlinking; SLL requires prev to be found or trick'),
('Swap K Nodes','Swapping kth node from beginning and kth from end in O(n) without actual node swap:','MCQ','HARD','DSA','Linked List','["Swap the nodes physically","Swap only the data values of the two nodes — O(n) to find both","Reverse the list","Use recursion"]','Swap only the data values of the two nodes — O(n) to find both'),
('Rotate LL','Rotate a linked list right by k places in O(n):','MCQ','HARD','DSA','Linked List','["Reverse technique","Find length, make circular, cut at (len - k % len) steps from tail","Sort","Detach and reattach"]','Find length, make circular, cut at (len - k % len) steps from tail'),
-- HARD CODING
('Reverse K Groups','Write C++ function to reverse nodes in K-groups. Signature: Node* reverseKGroup(Node* head, int k).','CODING','HARD','DSA','Linked List',NULL,'Node* reverseKGroup(Node* head,int k){Node* cur=head;int cnt=0;while(cur&&cnt<k){cur=cur->next;cnt++;}if(cnt<k)return head;Node* prev=nullptr,*c=head,*nxt;for(int i=0;i<k;i++){nxt=c->next;c->next=prev;prev=c;c=nxt;}head->next=reverseKGroup(c,k);return prev;}'),
('LRU Cache LL Code','Write C++ LRU Cache get(int key) using unordered_map and list<pair<int,int>>. Cache map maps key to list iterator. On hit move to front.','CODING','HARD','DSA','Linked List',NULL,'int get(int key){if(mp.find(key)==mp.end())return -1;cache.splice(cache.begin(),cache,mp[key]);return mp[key]->second;}'),
('Add Two Numbers','Write C++ to add two numbers as reversed linked lists. Signature: Node* addTwoNumbers(Node* l1, Node* l2).','CODING','HARD','DSA','Linked List',NULL,'Node* addTwoNumbers(Node* l1,Node* l2){Node dummy(0);Node* cur=&dummy;int carry=0;while(l1||l2||carry){int s=(l1?l1->data:0)+(l2?l2->data:0)+carry;carry=s/10;cur->next=new Node(s%10);cur=cur->next;if(l1)l1=l1->next;if(l2)l2=l2->next;}return dummy.next;}'),
('Palindrome Check LL','Write C++ to check if linked list is palindrome in O(n) O(1) space. Signature: bool isPalindrome(Node* head).','CODING','HARD','DSA','Linked List',NULL,'bool isPalindrome(Node* head){Node* slow=head,*fast=head;while(fast&&fast->next){slow=slow->next;fast=fast->next->next;}Node* prev=nullptr,*cur=slow;while(cur){Node* nxt=cur->next;cur->next=prev;prev=cur;cur=nxt;}Node* a=head,*b=prev;while(b){if(a->data!=b->data)return false;a=a->next;b=b->next;}return true;}'),
('Merge K Sorted LL Code','Write C++ merge K sorted lists using a min-heap. Signature: Node* mergeKLists(vector<Node*>& lists).','CODING','HARD','DSA','Linked List',NULL,'Node* mergeKLists(vector<Node*>& lists){auto cmp=[](Node* a,Node* b){return a->data>b->data;};priority_queue<Node*,vector<Node*>,decltype(cmp)> pq(cmp);for(auto h:lists)if(h)pq.push(h);Node dummy(0);Node* cur=&dummy;while(!pq.empty()){Node* top=pq.top();pq.pop();cur->next=top;cur=cur->next;if(top->next)pq.push(top->next);}return dummy.next;}'),

-- ================================================================
--  DSA / STACK  —  EASY
-- ================================================================
('Stack LIFO','A stack follows which principle?','MCQ','EASY','DSA','Stack','["FIFO","LILO","LIFO","Random access"]','LIFO'),
('Stack Push','The operation that adds an element to the top of a stack is called:','MCQ','EASY','DSA','Stack','["enqueue","dequeue","push","poll"]','push'),
('Stack Pop','The operation that removes the top element of a stack is called:','MCQ','EASY','DSA','Stack','["push","peek","dequeue","pop"]','pop'),
('Stack Peek','The operation that reads the top element WITHOUT removing it:','MCQ','EASY','DSA','Stack','["pop","push","peek / top","front"]','peek / top'),
('Stack Complexity','All fundamental stack operations (push, pop, peek) are:','MCQ','EASY','DSA','Stack','["O(n)","O(log n)","O(1)","O(n^2)"]','O(1)'),
('Stack Call','The function call stack in a CPU is used for:','MCQ','EASY','DSA','Stack','["Heap allocation","Sorting","Storing return addresses and local variables of function calls","Network communication"]','Storing return addresses and local variables of function calls'),
('Stack Undo','Which application naturally uses a stack?','MCQ','EASY','DSA','Stack','["BFS graph traversal","Undo/redo functionality","Database indexing","OS scheduling"]','Undo/redo functionality'),
('Stack Empty','A stack underflow occurs when:','MCQ','EASY','DSA','Stack','["Push is called on a full stack","Pop or peek is called on an empty stack","Stack is created","Two stacks are merged"]','Pop or peek is called on an empty stack'),
('Stack Full','A stack overflow in a fixed array stack occurs when:','MCQ','EASY','DSA','Stack','["Pop is called on an empty stack","Push is called on a full stack","Top exceeds int range","Stack is created"]','Push is called on a full stack'),
('Stack C++ STL','The C++ STL stack is in header:','MCQ','EASY','DSA','Stack','["<queue>","<list>","<stack>","<vector>"]','<stack>'),
('Stack DFS','DFS (Depth-First Search) graph traversal uses:','MCQ','EASY','DSA','Stack','["Queue","Heap","Stack (or recursion)","Set"]','Stack (or recursion)'),
('Stack Balanced','Balanced parentheses checking uses a stack where:','MCQ','EASY','DSA','Stack','["Every char is pushed","Opening brackets are pushed; closing brackets pop and verify match","Closing brackets are pushed","Numbers are pushed"]','Opening brackets are pushed; closing brackets pop and verify match'),
('Stack Reverse','To reverse a string using a stack: push all chars, then:','MCQ','EASY','DSA','Stack','["Push again","Pop all chars into a new string","Sort the stack","Peek only"]','Pop all chars into a new string'),
('Stack Postfix','Evaluating a postfix expression uses a stack where:','MCQ','EASY','DSA','Stack','["Operators are pushed, operands pop","Operands are pushed; when an operator is encountered, two operands are popped, result pushed","All tokens are pushed first","Operators are never pushed"]','Operands are pushed; when an operator is encountered, two operands are popped, result pushed'),
('Stack Vector','A C++ stack can be implemented using:','MCQ','EASY','DSA','Stack','["Only arrays","Only linked lists","vector, deque, or list as underlying container","Only queue"]','vector, deque, or list as underlying container'),
('Stack top()','In C++ STL, st.top() returns:','MCQ','EASY','DSA','Stack','["Removes and returns top","Returns bottom element","Returns reference to top element without removing","Returns stack size"]','Returns reference to top element without removing'),
('Stack size()','In C++ STL, st.size() returns:','MCQ','EASY','DSA','Stack','["Stack capacity","Top element index","Number of elements currently in the stack","Memory used"]','Number of elements currently in the stack'),
('Stack empty()','st.empty() returns true when:','MCQ','EASY','DSA','Stack','["Stack has one element","Stack has maximum elements","Stack has zero elements","Stack was just created"]','Stack has zero elements'),
('Stack Infix','Converting infix to postfix uses a stack to:','MCQ','EASY','DSA','Stack','["Hold all operands","Hold operators and manage precedence — pop when higher or equal precedence operator is seen","Hold only parentheses","Hold numbers only"]','Hold operators and manage precedence — pop when higher or equal precedence operator is seen'),
('Stack Recursion','Recursion can always be simulated using:','MCQ','EASY','DSA','Stack','["A queue","A heap","An explicit stack","A linked list only"]','An explicit stack'),
-- EASY CODING
('Stack Declare','Write C++ to declare a stack of integers named st and push 10 then 20.','CODING','EASY','DSA','Stack',NULL,'stack<int> st; st.push(10); st.push(20);'),
('Stack Pop Access','Write C++ to print the top of stack st, then remove it.','CODING','EASY','DSA','Stack',NULL,'cout << st.top(); st.pop();'),
('Stack Loop Print','Write C++ while-loop to print and pop all elements of stack st.','CODING','EASY','DSA','Stack',NULL,'while(!st.empty()){ cout<<st.top()<<" "; st.pop(); }'),
('Stack Balanced Simple','Write C++ to push an opening bracket to a char stack s and pop when closing bracket is found (single bracket type only, check match).','CODING','EASY','DSA','Stack',NULL,'if(c==\'(\') s.push(c); else { if(s.empty()||s.top()!=\'(\') return false; s.pop(); }'),
('Stack Reverse String','Write C++ to reverse string str using a stack<char>.','CODING','EASY','DSA','Stack',NULL,'stack<char> st; for(char c:str) st.push(c); string rev=""; while(!st.empty()){rev+=st.top();st.pop();}'),

-- ================================================================
--  DSA / STACK  —  MEDIUM
-- ================================================================
('Min Stack Concept','A Min Stack supports O(1) getMin() by:','MCQ','MEDIUM','DSA','Stack','["Sorting on every push","Maintaining a second auxiliary stack of minimums","Scanning all elements on getMin","Using a sorted array"]','Maintaining a second auxiliary stack of minimums'),
('Monotonic Stack','A monotonic stack maintains elements in:','MCQ','MEDIUM','DSA','Stack','["Sorted order using sorting","Monotonically increasing or decreasing order","Hash order","Insertion order"]','Monotonically increasing or decreasing order'),
('Next Greater','Next Greater Element for each array position uses a monotonic stack in:','MCQ','MEDIUM','DSA','Stack','["O(n^2)","O(n log n)","O(n)","O(1)"]','O(n)'),
('Valid Parens','Checking valid parentheses with {, [, ( uses a stack. Total time complexity:','MCQ','MEDIUM','DSA','Stack','["O(n^2)","O(n log n)","O(n)","O(1)"]','O(n)'),
('Shunting Yard','Shunting-Yard algorithm converts infix to postfix handling precedence by:','MCQ','MEDIUM','DSA','Stack','["Using two queues","Operator stack: pop operators of >= precedence before pushing new operator","Hash map of precedence","Sorting operators"]','Operator stack: pop operators of >= precedence before pushing new operator'),
('Stock Span','The Stock Span problem (how many consecutive days before current with price <=) uses:','MCQ','MEDIUM','DSA','Stack','["Two pointer","Monotonic decreasing stack of indices — O(n)","Sorting","Prefix array"]','Monotonic decreasing stack of indices — O(n)'),
('Eval Postfix','Evaluating postfix expression 2 3 4 * + yields:','MCQ','MEDIUM','DSA','Stack','["14","20","9","24"]','14'),
('Largest Rect Approach','Largest Rectangle in Histogram uses a monotonic ___ stack.','MCQ','MEDIUM','DSA','Stack','["decreasing — pop when shorter bar found","increasing","random","sorted"]','decreasing — pop when shorter bar found'),
('Two Stacks Queue','Implementing a queue using two stacks: amortized enqueue and dequeue are:','MCQ','MEDIUM','DSA','Stack','["O(n) each","O(1) amortized each","O(log n) each","O(n) enqueue, O(1) dequeue"]','O(1) amortized each'),
('Max Area Rect','Maximum rectangle in binary matrix uses Largest-Rect-in-Histogram approach per row. Complexity for m x n matrix:','MCQ','MEDIUM','DSA','Stack','["O(m*n^2)","O(m*n)","O(m^2*n)","O(n^2)"]','O(m*n)'),
('Decode String','Decode string like 3[a2[bc]] uses a stack to:','MCQ','MEDIUM','DSA','Stack','["Sort characters","Push current string and repetition count when [ is found, pop and expand on ]","Use BFS","Recursion only"]','Push current string and repetition count when [ is found, pop and expand on ]'),
('Score Parens','Score of Parentheses: () = 1, AB = A+B, (A) = 2*A. A stack tracks:','MCQ','MEDIUM','DSA','Stack','["Open brackets count","Current depth scores — push 0 on (, on ) compute score","Total score only","Char counts"]','Current depth scores — push 0 on (, on ) compute score'),
('Remove K Digits','Remove K digits to form smallest number using a monotonic stack removes:','MCQ','MEDIUM','DSA','Stack','["K largest digits","Digits greater than the next digit (greedy) — maintains non-decreasing stack","Random digits","Leading zeros"]','Digits greater than the next digit (greedy) — maintains non-decreasing stack'),
('132 Pattern','Detecting a 132 pattern (i<j<k, ai<ak<aj) efficiently uses:','MCQ','MEDIUM','DSA','Stack','["Two pointer","O(n) monotonic stack scanning right to left, tracking the best third element","Sorting","Brute O(n^3)"]','O(n) monotonic stack scanning right to left, tracking the best third element'),
('Asteroid Collision','Asteroid Collision problem (positive moves right, negative left, smaller explodes) is solved with a:','MCQ','MEDIUM','DSA','Stack','["Queue","Priority queue","Stack — process each asteroid against stack top","Sorting"]','Stack — process each asteroid against stack top'),
('Basic Calculator','Basic Calculator I (with +,-,() no multiplication) uses a stack to:','MCQ','MEDIUM','DSA','Stack','["Store all numbers","Store result and sign before each open parenthesis, pop on )","Track operator precedence","Handle recursion"]','Store result and sign before each open parenthesis, pop on )'),
('Simplify Path','Simplifying a Unix path /a/b/../c uses a stack where:','MCQ','MEDIUM','DSA','Stack','["All tokens are pushed",".. pops the last directory; valid names are pushed","/ is pushed","Only letters are pushed"]','.. pops the last directory; valid names are pushed'),
('Min in Stack Pop','When the top of the aux-min stack equals the popped element in a Min Stack:','MCQ','MEDIUM','DSA','Stack','["Do nothing","Also pop the aux min stack","Reset min stack","Sort again"]','Also pop the aux min stack'),
('Evaluate RPN','Evaluate Reverse Polish Notation. Token 2,1,+,3,*: result?','MCQ','MEDIUM','DSA','Stack','["7","9","5","8"]','9'),
('Stack Sort','Sorting a stack using only stack operations (push, pop, peek, isEmpty) gives time complexity:','MCQ','MEDIUM','DSA','Stack','["O(n log n)","O(n)","O(n^2)","O(log n)"]','O(n^2)'),
-- MEDIUM CODING
('Min Stack Code','Write C++ MinStack class with push(int), pop(), top(), and getMin(). Use two stacks: st and minSt.','CODING','MEDIUM','DSA','Stack',NULL,'class MinStack{stack<int> st,minSt;public:void push(int v){st.push(v);if(minSt.empty()||v<=minSt.top())minSt.push(v);}void pop(){if(st.top()==minSt.top())minSt.pop();st.pop();}int top(){return st.top();}int getMin(){return minSt.top();}};'),
('Valid Parens Code','Write C++ isValid(string s) for balanced brackets {[()]} using stack<char>.','CODING','MEDIUM','DSA','Stack',NULL,'bool isValid(string s){stack<char> st;for(char c:s){if(c==\'(\'||c==\'[\'||c==\'{\')st.push(c);else{if(st.empty())return false;char t=st.top();st.pop();if((c==\')\'&&t!=\'(\')||(c==\']\'&&t!=\'[\')||(c==\'}\'&&t!=\'{\'))return false;}}return st.empty();}'),
('Stock Span Code','Write C++ stockSpan(vector<int>& prices) returning vector<int> spans using monotonic stack of indices.','CODING','MEDIUM','DSA','Stack',NULL,'vector<int> stockSpan(vector<int>& p){int n=p.size();vector<int> res(n);stack<int> st;for(int i=0;i<n;i++){while(!st.empty()&&p[st.top()]<=p[i])st.pop();res[i]=st.empty()?i+1:i-st.top();st.push(i);}return res;}'),
('Next Greater Code','Write C++ nextGreaterElement(vector<int>& a) returning vector<int> using monotonic decreasing stack.','CODING','MEDIUM','DSA','Stack',NULL,'vector<int> nextGreaterElement(vector<int>& a){int n=a.size();vector<int> res(n,-1);stack<int> st;for(int i=0;i<n;i++){while(!st.empty()&&a[st.top()]<a[i]){res[st.top()]=a[i];st.pop();}st.push(i);}return res;}'),
('Two Stack Queue','Write C++ Queue using two stacks: enqueue(int) pushes to s1; dequeue() transfers s1 to s2 if s2 is empty then pops s2.','CODING','MEDIUM','DSA','Stack',NULL,'class MyQueue{stack<int> s1,s2;public:void enqueue(int x){s1.push(x);}int dequeue(){if(s2.empty())while(!s1.empty()){s2.push(s1.top());s1.pop();}int v=s2.top();s2.pop();return v;}};'),

-- ================================================================
--  DSA / STACK  —  HARD
-- ================================================================
('Max Freq Stack','MaxFreqStack supports push, pop that removes the most frequent element (ties broken by recency). Implementation uses:','MCQ','HARD','DSA','Stack','["Single priority queue","Map of frequency to stack + freq map + maxFreq tracker — all O(1)","Sorted linked list","Binary heap only"]','Map of frequency to stack + freq map + maxFreq tracker — all O(1)'),
('Trapping Rain Stack','Trapping Rain Water using a stack: pop when current height > stack top to compute trapped water. Time:','MCQ','HARD','DSA','Stack','["O(n^2)","O(n log n)","O(n)","O(n^3)"]','O(n)'),
('Maximal Rect','Maximal rectangle in binary matrix: computed in O(m*n) by applying:','MCQ','HARD','DSA','Stack','["2D DP only","Largest Rectangle in Histogram for each row using stack","BFS","DFS"]','Largest Rectangle in Histogram for each row using stack'),
('Remove Dup Letters','Remove Duplicate Letters (result is smallest lexicographic subsequence with all chars once). Algorithm?','MCQ','HARD','DSA','Stack','["Sort then deduplicate","Greedy monotonic stack: pop larger char if it appears later, push current","BFS","Backtracking"]','Greedy monotonic stack: pop larger char if it appears later, push current'),
('Flatten Nested','Flatten nested list iterator uses a stack where:','MCQ','HARD','DSA','Stack','["All integers are pre-extracted","List of NestedIntegers is pushed; on next(), flatten from stack top until integer is found","BFS queue","Recursion only"]','List of NestedIntegers is pushed; on next(), flatten from stack top until integer is found'),
('Online Stock Span','Online Stock Span merges consecutive days with lower or equal price. Stack stores (price,span) pairs. Each price is processed:','MCQ','HARD','DSA','Stack','["O(n) per element worst case","Amortized O(1) — each price pushed and popped at most once","O(log n) with binary search","O(n^2) total"]','Amortized O(1) — each price pushed and popped at most once'),
('Car Fleet','Car Fleet problem: fleet forms when a slower car catches up. Stack approach processes cars sorted by position, storing travel times. Complexity?','MCQ','HARD','DSA','Stack','["O(n^2)","O(n log n) — dominated by sort","O(n)","O(n log^2 n)"]','O(n log n) — dominated by sort'),
('Exclusive Time Func','Exclusive time of functions using a log of start/end events uses a stack to track:','MCQ','HARD','DSA','Stack','["All completed functions","Currently running function — on end, add elapsed time to its exclusive time","Return values","Function pointers"]','Currently running function — on end, add elapsed time to its exclusive time'),
('Robot Seq','Daily Temperatures: find days until a warmer day. Uses:','MCQ','HARD','DSA','Stack','["Two pointer","Monotonic decreasing stack of indices — O(n)","Sorting","Binary search per element"]','Monotonic decreasing stack of indices — O(n)'),
('132 Stack Solution','132 Pattern detection: scanning right to left, the stack stores candidates for the third element (k). A variable tracks:','MCQ','HARD','DSA','Stack','["The minimum so far","The best (largest) third element found below the last popped element (s3)","The middle element","All candidates"]','The best (largest) third element found below the last popped element (s3)'),
('Stack Sortable','A sequence is stack-sortable if it can be sorted using a single stack with push/pop operations to output in sorted order. This is equivalent to the sequence containing no ___ pattern.','MCQ','HARD','DSA','Stack','["123","132","213","231"]','231'),
('Iterative InOrder','Iterative in-order traversal of BST uses a stack: push left spine, then on pop:','MCQ','HARD','DSA','Stack','["Recurse right","Process node, then push right subtree''s left spine","Pop again","Use queue for right"]','Process node, then push right subtree''s left spine'),
('Ceil Stack','Given a stack with natural numbers, to implement a ceil operation (find smallest element >= x) in O(n):','MCQ','HARD','DSA','Stack','["Sort the stack","Pop until >= x is found, track answer, then restore — O(n) amortized","Use binary search","Use priority queue"]','Pop until >= x is found, track answer, then restore — O(n) amortized'),
('K Stacks Array','Implement K stacks in a single array of size N efficiently (no wasted space) uses:','MCQ','HARD','DSA','Stack','["N/K slots each","Free list + top[] + next[] arrays — O(1) push and pop","Sorting","Extra linked list"]','Free list + top[] + next[] arrays — O(1) push and pop'),
('Stack DP','Some DP problems are solved using a stack. The pattern "for each element, combine with previous results while condition holds" is called:','MCQ','HARD','DSA','Stack','["Memoization","DP with monotonic stack — avoids redundant recomputation","Tabulation","Greedy"]','DP with monotonic stack — avoids redundant recomputation'),
('Infix Complex','Converting complex infix with right-associative operators (like ^) to postfix: right-associative means when same precedence, pop only if:','MCQ','HARD','DSA','Stack','["Stack top has higher precedence","Stack top has strictly higher precedence (not equal)","Stack top has lower precedence","Stack is empty"]','Stack top has strictly higher precedence (not equal)'),
('Balanced Ternary','A stack of size n can hold at most n elements. Using it to check balanced ternary brackets adds complexity of:','MCQ','HARD','DSA','Stack','["O(n^2)","O(n)","O(log n)","O(1)"]','O(n)'),
('Stack Interview','Given a stack, to get the bottom element without extra data structures requires:','MCQ','HARD','DSA','Stack','["Impossible","Recursion: pop all, get last, push back — O(n) space on call stack","Extra variable","Sort the stack"]','Recursion: pop all, get last, push back — O(n) space on call stack'),
('Plate Stack','Plate of stacks: push to last stack if capacity not exceeded, else create new stack. Pop from last stack, remove it if empty. Get peak from any sub-stack uses:','MCQ','HARD','DSA','Stack','["Single stack","Vector of stacks with O(1) amortized push/pop and O(1) popAt for any index","Linked list of stacks","Priority queue"]','Vector of stacks with O(1) amortized push/pop and O(1) popAt for any index'),
('Weird Stack','A stack that supports push, pop, and getMiddle (middle element) in O(1) can be implemented using:','MCQ','HARD','DSA','Stack','["Two stacks","A doubly linked list with a middle pointer, updated on push/pop","Array with midpoint tracking","Three stacks"]','A doubly linked list with a middle pointer, updated on push/pop'),
-- HARD CODING
('Daily Temperatures','Write C++ dailyTemperatures(vector<int>& t) returning days until warmer using monotonic decreasing stack of indices.','CODING','HARD','DSA','Stack',NULL,'vector<int> dailyTemperatures(vector<int>& t){int n=t.size();vector<int> res(n,0);stack<int> st;for(int i=0;i<n;i++){while(!st.empty()&&t[st.top()]<t[i]){res[st.top()]=i-st.top();st.pop();}st.push(i);}return res;}'),
('Trapping Rain Stack Code','Write C++ trap(vector<int>& h) for Trapping Rain Water using a stack.','CODING','HARD','DSA','Stack',NULL,'int trap(vector<int>& h){int n=h.size(),res=0;stack<int> st;for(int i=0;i<n;i++){while(!st.empty()&&h[st.top()]<h[i]){int bot=st.top();st.pop();if(st.empty())break;int dist=i-st.top()-1;int bounded=min(h[i],h[st.top()])-h[bot];res+=bounded*dist;}st.push(i);}return res;}'),
('Remove Dup Letters Code','Write C++ removeDuplicateLetters(string s) using monotonic greedy stack. Result is smallest lex subsequence with each letter once.','CODING','HARD','DSA','Stack',NULL,'string removeDuplicateLetters(string s){vector<int> cnt(26,0);vector<bool> inStk(26,false);for(char c:s)cnt[c-\'a\']++;stack<char> st;for(char c:s){cnt[c-\'a\']--;if(inStk[c-\'a\'])continue;while(!st.empty()&&st.top()>c&&cnt[st.top()-\'a\']>0){inStk[st.top()-\'a\']=false;st.pop();}st.push(c);inStk[c-\'a\']=true;}string res="";while(!st.empty()){res+=st.top();st.pop();}reverse(res.begin(),res.end());return res;}'),
('Maximal Rectangle Code','Write C++ maximalRectangle(vector<vector<char>>& matrix) using largest-rect-in-histogram approach.','CODING','HARD','DSA','Stack',NULL,'int maximalRectangle(vector<vector<char>>& m){if(m.empty())return 0;int n=m[0].size(),res=0;vector<int> h(n,0);for(auto& row:m){for(int i=0;i<n;i++)h[i]=row[i]==\'1\'?h[i]+1:0;stack<int> st;for(int i=0;i<=n;i++){int cur=i==n?0:h[i];while(!st.empty()&&h[st.top()]>cur){int ht=h[st.top()];st.pop();int w=st.empty()?i:i-st.top()-1;res=max(res,ht*w);}st.push(i);}}return res;}'),
('Basic Calculator Code','Write C++ calculate(string s) for basic calculator (+,-,() no multiply). Use stack to save result and sign on (.','CODING','HARD','DSA','Stack',NULL,'int calculate(string s){stack<int> st;int res=0,sign=1,i=0;while(i<s.size()){char c=s[i];if(isdigit(c)){int num=0;while(i<s.size()&&isdigit(s[i]))num=num*10+(s[i++]-\'0\');res+=sign*num;continue;}else if(c==\'+\')sign=1;else if(c==\'-\')sign=-1;else if(c==\'(\'){st.push(res);st.push(sign);res=0;sign=1;}else if(c==\')\'){res=st.top()*res;st.pop();res+=st.top();st.pop();}i++;}return res;}');

-- (Queue, Tree, Graph continue in seed_questions_v2_part3.sql)

SELECT prep_field, topic, difficulty, type, COUNT(*) AS cnt
FROM questions
GROUP BY prep_field, topic, difficulty, type
ORDER BY prep_field, topic, difficulty, type;
